### ISSUE TITLE
HTML tables or reference a fig as a tbl?

### ISSUE THREAD

**Issue by izaakm** [lierdakil/pandoc-crossref#104]
The basic problem that I'm having is actually using tables in markdown, which is very tedious for complex tables. 

**I would like to either use html tables, or just arbitrarily apply a `tbl` reference to a `fig`.** Is something like the below possible? I've tried several variations of this and can't get it to work.

Note: For this example I'm outputting html, but would need to produce documents in word (docx) or pdf format as well (`pandoc -F pandoc-crossref -F pandoc-citeproc test.md -o test.html`).

I expected html table references to work something like this, but it wouldn't work for me:

```
<div id="tbl:table">
<table>
<tr>
<td>my data</td>
</tr>
</table>
</div>

Reference to [@tbl:table]
```

produces:

```
<div id="tbl:table">
<table>
<tr>
<td>
my data
</td>
</tr>
</table>
</div>
<p>Reference to tbl. <strong>¿tbl:table?</strong></p>
```

I also tried arbitrarily assigning an image using a `tbl` reference, but that didn't work either, eg ...

```
![An image of a table](table.png){#tbl:table}

Reference to [@tbl:table]
```

produces ...

```
<div class="figure">
<img src="table.png" alt="An image of a table" id="tbl:table" />
<p class="caption">An image of a table</p>
</div>
<p>Reference to tbl. <strong>¿tbl:table?</strong></p>
```

**Comment by lierdakil** [comment]
So a little bit of behind-the-scenes. When I started on this project in the first place, I used `tbl:` etc prefixes to simplify passing reference type around. This is a relatively bad design decision, and I've been meaning to rethink this, but due to lack of time it never got off the ground really.

So long story short, `tbl:` prefix as of the time of writing only works for things Pandoc considers to be tables. HTML tables are read as raw HTML blocks I believe, so that's why that doesn't work. Images don't work because, well, those are considered to be figures, not tables.

So what you can do, besides hacking on pandoc-crossref, is you could slap together a filter that would convert HTML tables back to Markdown. I don't know how complex your tables are, and if those *can* even be represented in Markdown and/or how Pandoc handles that in other output formats, but consider something like this:

(htmltables.hs)
```haskell
import Text.Pandoc
import Text.Pandoc.JSON
import Data.List

main :: IO ()
main = toJSONFilter go
  where
    go x@(Div (id',_cls,attr) _)
      | "tbl:" `isPrefixOf` id'
      , Just "html" == "data-type" `lookup` attr
      = case readHtml def (writeMarkdown def (Pandoc mempty [x])) of
          Right (Pandoc _ tbs) -> tbs
          Left e -> error $ show e
    go x = [x]
```

for each `<div id="tbl:..." data-type="html">...</div>` it dumps original Md source contained witthin, re-reads it as HTML, and pastes what it read into AST. So, for example, this:

```markdown
<div id="tbl:table" data-type="html">
  <table>
   <caption>Footwear size table</caption>
   <tr>
    <th>Russia</th>
    <th>Great Britain</th>
    <th>Europe</th>
    <th>Foot length, cm</th>
   </tr>
   <tr><td>34,5</td><td>3,5</td><td>36</td><td>23</td></tr>
   <tr><td>35,5</td><td>4</td><td>36⅔</td><td>23–23,5</td></tr>
   <tr><td>36</td><td>4,5</td><td>37⅓</td><td>23,5</td></tr>
   <tr><td>36,5</td><td>5</td><td>38</td><td>24</td></tr>
   <tr><td>37</td><td>5,5</td><td>38⅔</td><td>24,5</td></tr>
   <tr><td>38</td><td>6</td><td>39⅓</td><td>25</td></tr>
   <tr><td>38,5</td><td>6,5</td><td>40</td><td>25,5</td></tr>
   <tr><td>39</td><td>7</td><td>40⅔</td><td>25,5–26</td></tr>
   <tr><td>40</td><td>7,5</td><td>41⅓</td><td>26</td></tr>
   <tr><td>40,5</td><td>8</td><td>42</td><td>26,5</td></tr>
   <tr><td>41</td><td>8,5</td><td>42⅔</td><td>27</td></tr>
   <tr><td>42</td><td>9</td><td>43⅓</td><td>27,5</td></tr>
   <tr><td>43</td><td>9,5</td><td>44</td><td>28</td></tr>
   <tr><td>43,5</td><td>10</td><td>44⅔</td><td>28–28,5</td></tr>
   <tr><td>44</td><td>10,5</td><td>45⅓</td><td>28,5–29</td></tr>
   <tr><td>44,5</td><td>11</td><td>46</td><td>29</td></tr>
   <tr><td>45</td><td>11,5</td><td>46⅔</td><td>29,5</td></tr>
   <tr><td>46</td><td>12</td><td>47⅓</td><td>30</td></tr>
   <tr><td>46,5</td><td>12,5</td><td>48</td><td>30,5</td></tr>
   <tr><td>47</td><td>13</td><td>48⅔</td><td>31</td></tr>
   <tr><td>48</td><td>13,5</td><td>49⅓</td><td>31,5</td></tr>
  </table>
</div>

Reference to [@tbl:table]
```
when run through
`pandoc -F ./htmltables.hs -F pandoc-crossref /tmp/test.md -t markdown` (you can of course use other output formats besides markdown)

turns into something like this:

```markdown
<div id="tbl:table" data-type="html">

  Russia   Great Britain   Europe   Foot length, cm
  -------- --------------- -------- -----------------
  34,5     3,5             36       23
  35,5     4               36⅔      23–23,5
  36       4,5             37⅓      23,5
  36,5     5               38       24
  37       5,5             38⅔      24,5
  38       6               39⅓      25
  38,5     6,5             40       25,5
  39       7               40⅔      25,5–26
  40       7,5             41⅓      26
  40,5     8               42       26,5
  41       8,5             42⅔      27
  42       9               43⅓      27,5
  43       9,5             44       28
  43,5     10              44⅔      28–28,5
  44       10,5            45⅓      28,5–29
  44,5     11              46       29
  45       11,5            46⅔      29,5
  46       12              47⅓      30
  46,5     12,5            48       30,5
  47       13              48⅔      31
  48       13,5            49⅓      31,5

  : Table 1: Footwear size table

</div>

Reference to tbl. 1
```

This way you could use other formats besides HTML if you wanted to.

As for using images, this is horrible and I do not recommend it, but an image inside a single-cell table *will* be treated as a table.

**Comment by izaakm** [comment]
Thanks for you reply. I did end up doing something like actually, just manually for the tables that I had and it did work pretty well. 

In case anyone else is interested, I moved all of my html tables to their own files, and then for each one I did something like this (on OS X):

    pandoc table-fungal-enzymes.html -t markdown | pbcopy 

And then pasted them back in to the markdown document. This way I saved the html in case I needed to edit it again. I'll have to check out `-F ./htmltables.hs`.

As far as the images, I was just thinking of that bc I thought it might be easy to make my table look pretty in Excel or Keynote and then save it as an image to use directly. It's just that it would still need to be referenced in the text with Tables and not with Figures.

**Comment by lierdakil** [comment]
Well, let's just say that my aversion to images-as-tables comes from some experience with using Markdown for academic writing (journal articles). Editors often complain about hard-rendered subfigure captions (which I sometimes can't help), and I believe those same editors would figuratively go insane if they saw a png image of a table in place of a table :)

**Comment by izaakm** [comment]
Yes I see what you mean. In a professional context, I don't think I would advocate for that implementation. Sometimes though, I just need to to turn in my homework.
