### ISSUE TITLE
Markdown: bracketed multi-reference citations require semicolon separator

### ISSUE THREAD

**Issue by dhimmel** [lierdakil/pandoc-crossref#110]
I'm using pandoc and pandoc-citeproc to automatically generate references and build the bibliography from markdown source. We [encountered an issue](https://github.com/greenelab/deep-review/issues/290) where multiple references inside brackets do not render properly if they're space-only separated.

For example, the markdown source of `[@ref_1 @ref_2 @ref_3]` will result in an inline reference of `[1]` with a bibliography that includes records for 1, 2, & 3.

Everything works if we add a semicolon separator `[@ref_1; @ref_2; @ref_3]`. This syntax results in the proper inline reference of `[1-3]`.

So not sure if this is the intended behavior (that semicolons are required). However, the behavior of only showing one inline reference but putting all references in the bibliography is odd.

From a simplicity and consistency standpoint, it would be nice to be able to omit these semicolons (assuming that won't break existing functionality).

**Comment by lierdakil** [comment]
Um. Did you mean to file this under https://github.com/jgm/pandoc-citeproc ? Anyway...

FWIW, `[@ref_1 @ref_2 @ref_3]` is treated as `@ref_1` with suffix ` @ref_2 @ref_3` by Pandoc.
If your csl silently drops reference suffixes, it's not Pandoc's fault.

And yes, semicolons are required as a separator, since reference keys can be surrounded by arbitrary Markdown.

**Comment by dhimmel** [comment]
> Did you mean to file this under `jgm/pandoc-citeproc`?

@lierdakil indeed. Oops.

Anyways thanks for answering my question. I didn't know about the suffix functionality.
