### ISSUE TITLE
Support for referencing chapters

### ISSUE THREAD

**Issue by Alxandr** [lierdakil/pandoc-crossref#114]
Please support references to chapters. Or tell me what I'm doing wrong :P.

I have a latex template file with `\chapter{Name}\label{cha:2}` and in my markdown I have `[@cha:2]`. This does not get turned into a `\cref`, but instead turns into `\autocite`.

**Comment by lierdakil** [comment]
For one, pandoc-crossref doesn't know about your LaTeX template, and since `cha:2` isn't defined in source Markdown, it assumes it's a citation. Drawback of sharing syntax.

Besides, `cha` prefix isn't defined as a reference prefix.

You could define your chapter as a top-level Markdown header and pass `--top-level-division=chapter` (or just `--chapters`, although it's deprecated) to Pandoc. Bear in mind, you might want to also add `-Mchapters` (or `chapters: true` to metadata) if you want pandoc-crossref to be chapter-aware. Note that you *have* to use `sec:` prefix.

**Comment by Alxandr** [comment]
Hmm. Cleveref got `cha:` prefix just fine. I can't use `--top-level-division=chapter` because of how I've built up my project. Is there any way I could feed `pandoc-crossref` a list of pre-defined symbols?

Also, this whole issue (which I now see is bigger than I first assumed) was about adding `cha` as a valid prefix.

**Comment by lierdakil** [comment]
Apparently I was mistaken about this:

> For one, pandoc-crossref doesn't know about your LaTeX template, and since cha:2 isn't defined in source Markdown, it assumes it's a citation. Drawback of sharing syntax.

Actually, it doesn't check in LaTeX output. So the actual problem is with `cha` prefix.

> Cleveref got cha: prefix just fine.

Cleveref doesn't care about prefixes at all, IIRC. Prefixes are actually just a way to disambiguate between citations and references.

> I can't use `--top-level-division=chapter` because of how I've built up my project. 

Frankly, I would imagine it's nothing a `sed` script couldn't fix... I understand it's a hassle, but I'm short on time right now, so I can't whip up a new release quickly. Besides, if you target output formats besides LaTeX, you'll *have* to include a thing you're referencing into source Markdown, no way around that. So there's that.

> Is there any way I could feed pandoc-crossref a list of predefined symbols?

No. Not at the moment at least. And it would be a rather problematic thing to allow that in general, although doable in principle.

> about adding `cha` as a valid prefix

Problem is, Markdown doesn't have a 'chapter' entity. So that'd be somewhat problematic, at least in how the whole thing is setup currently. Making prefixes arbitrary and configurable has been on my to-do list for a while now, but I never found time to even design the thing properly, let alone implement it. So yeah. Besides, this entails a huge API change, so that's also something to keep in mind.

So for now, I could suggest a few workarounds.
If you manage to set the thing up to use with `--chapters`, switching to `sec:chapter2` and referencing by number only (e.g. `[-@sec:chapter2]`) -- assuming you don't want it to show up as 'sec. 2',  will work in all output formats. If you're targeting LaTeX only, using raw `\cref{cha:2}` is also an option, but it obviously won't work with other outputs.

**Comment by Alxandr** [comment]
Currently I'm doing `\cref{cha:2}`, and just biting the HTML bullet when that time comes. PDF is most important to get finished.

**Comment by Alxandr** [comment]
Btw; you said `pandoc-citerec` only support references defined in the markdown, yes? How am I able to get it to work across markdown documents then? My `Makefile` runs `pandoc` on one markdown-file at a time, so it should not know about any labels defined in markdown, no?

**Comment by lierdakil** [comment]
Um. I have no idea what's `pandoc-citerec`. Do you mean `pandoc-citeproc`? That thing uses external citation database (`.bibtex` file for instance). This approach is not applicable for internal references obviously.

A way to get multi-file Markdown document to work (admittedly, rather stupid way, but it works for me most of the time) is to feed Pandoc several files in order. For example, `pandoc -F pandoc-crossref introduction.md chapter1.md chapter2.md ... conclusion.md`. Pandoc will internally concatenate documents in order of appearance and produce output as if it was a single huge file. No other options currently, but I'm generally aware that this can be a problem, so I'm thinking of ways to fix this. Nothing in particular yet though.

**Comment by Alxandr** [comment]
Sorry, I miswrote. And also you misunderstood. I already have references working internally using `pandoc-crossref` on different chapters. Why it works, I have no clue, but it does.

**Comment by lierdakil** [comment]
Ah, well, with LaTeX it does as long as you compile resulting LaTeX together, since whole cross-referencing thing is offloaded to LaTeX engine. With other output formats, it would be another story.

**Comment by Alxandr** [comment]
Right. And my original query was basically just since `[@sec:foo]` works (in latex, even when `pandoc-crossref` doesn't know about `sec:foo`), why can't `chap:foo` work. Though you've mostly answered it already, just figured I'd make my original inquiry understood better :).

**Comment by nim65s** [comment]
I was trying to name my refs {#part:something} & {#chap:somethingelse} too. The error message is a bit confusing: `pandoc-citeproc: reference part:something not found`

**Comment by lierdakil** [comment]
@nim65s -- that's expected. Anything pandoc-crossref doesn't recognize as a reference is passed on to pandoc-citeproc (if it's enabled). And neither `part` nor `chap` is considered a valid reference prefix.

**Comment by rriemann** [comment]
I would like to use `@thm:blub` to reference to a theorem labeled with `\label{thm:blub}`. I use cleveref which is configured for this. However, I cannot tell crossref to convert my ref to `\cref{thm:blub}`. :(

**Comment by lierdakil** [comment]
@rriemann, well, you won't be able to anyway, since this wouldn't make sense in most output formats except LaTeX. Just use inline LaTeX if targeting LaTeX exclusively.

**Comment by lierdakil** [comment]
I'll close this in favor of #84.
