### ISSUE TITLE
Option "listtingTitle" does not seem to work

### ISSUE THREAD

**Issue by azusa** [lierdakil/pandoc-crossref#118]
I can change the prefix of list from "lst." to "リスト" using by "lstPrefix" option.
But I cannot change the title of list from "Listing" to "リスト" using by "listingTitle" option.
I ｗonder that [option.hs](https://github.com/lierdakil/pandoc-crossref/blob/6e0fb77d329516001045eaab3126017d53ce649c/lib/Text/Pandoc/CrossRef/Util/Options.hs)  does not have "listingTitle" field.
So would you tell me that how to change a title of list?

**Comment by lierdakil** [comment]
`listingTitle` should generally work. Neither it, nor any other `*Title` options are defined in `Options.hs` because those are actually string-indexed template variables, with accessors generated using a bit of TH magic, default values defined [here](https://github.com/lierdakil/pandoc-crossref/blob/master/lib/Text/Pandoc/CrossRef/Util/Settings.hs#L50) and used, among other places, [here](https://github.com/lierdakil/pandoc-crossref/blob/master/lib/Text/Pandoc/CrossRef/Util/Settings.hs#L71).

This:

``````markdown
---
listingTitle: リスト
codeBlockCaptions: true
---

```{#lst:code .haskell}
a = listing
```

: A caption
``````

works as expected in any output format (with a caveat that LaTeX has to be configured to support katakana -- or any international symbols for that matter).

However, if you're using `listings` package with LaTeX (i.e. you invoke Pandoc with `--listings` opiton),  then you'll need to configure this package manually, either via a custom LaTeX template, or with header-includes. For example, 

``````markdown
---
listingTitle: リスト
codeBlockCaptions: true
listings: true
header-includes:
    - \renewcommand{\lstlistingname}{リスト}
---

```{#lst:code .haskell}
a = listing
```

: A caption
``````

This is mostly an oversight on my part.

Let me know if this works out for you.

**Comment by azusa** [comment]
I got change `listingTitle`. It's by mistake.
I use include a header (pandoc `--include-in-header=` option)  in order to using UTF-8 CJK String by lualatef.
So I pasted  default pandoc-crossref header below, but ｔhat setting remained the default.
Thus there is  a header includeing `\floatname{codelisting}{Listing}` ...
I changed header using ` \floatname{codelisting}{リスト}` , then I got work well.

```
\usepackage{subfig}
\AtBeginDocument{%
\renewcommand*\figurename{Figure}
\renewcommand*\tablename{Table}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{List of Figures}
\renewcommand*\listtablename{List of Tables}
}
\usepackage{float}
\floatstyle{ruled}
\makeatletter
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\makeatother
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
```
I am sorry for my mｉｓｕｎｄｅｒｓｔａｎｄｉｎｇ, thaks for your kindness help!
