### ISSUE TITLE
too much space between "Figure" and reference

### ISSUE THREAD

**Issue by JonathanReeve** [lierdakil/pandoc-crossref#12]
This filter seems to put an additional space between `Figure` and the number, so instead of `Figure~\ref` it writes: `Figure~ \ref`, which makes LaTeX output `Figure 5` with two spaces between `Figure` and `5`. Screenshot: 

![screenshot from 2015-05-03 12-56-07](https://cloud.githubusercontent.com/assets/1843676/7445995/b04dab38-f196-11e4-8930-b5fdcacc825f.png)

**Comment by lierdakil** [comment]
Right. This is due to fix for #11 (since multiple spaces would be typeset as one by LaTeX, but `~ ` is not). There is a corner case which I'm unsure about though. If there are multiple references, and cleveref is not used, then it would be expanded to
```latex
Figure~ \ref{a}, \ref{b}, \ref{c}
```
There are two options to fix this. First is to just strip leading spaces, which would give
```latex
Figure~\ref{a}, \ref{b}, \ref{c}
```
Second is to use non-breaking spaces all the way, e.g.
```latex
Figure~\ref{a},~\ref{b},~\ref{c}
```
Which one would suit you best?

**Comment by JonathanReeve** [comment]
Cool. The first of those two options sounds the best to me. I myself rarely have more than one reference at a time, but I imagine that multiple references could probably be wrapped after the first one.

**Comment by lierdakil** [comment]
Ok, I've pushed 0.1.0.2 to hackage.

**Comment by JonathanReeve** [comment]
Awesome.
