### ISSUE TITLE
in-text citation with notice in brackets does not work with other references

### ISSUE THREAD

**Issue by rriemann** [lierdakil/pandoc-crossref#121]
The syntax of in-text citations is:

```md
@smith04 [p. 33] says blah.
```

This works for me. Then I try:

```md
@smith04 [cf. @sec:introduction]
```

This does not produce the right latex. I found a workaround in writing

```md
@smith04 [cf. \cref{sec:introduction}]
```

, but I would be interested in a real fix.

pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1.1, skylighting 0.1.1.5
pandoc-crossref 0.2.4.1 (I guess, how to check that?)

I already created a pandoc issue https://github.com/jgm/pandoc/issues/3740 but got sent here.

**Comment by lierdakil** [comment]
`@smith04 [cf. @sec:introduction]` is parsed as `[[in-text citation] [normal-citation-with-prefix]]`, i.e. since brackets contain citation `@sec:introduction`, it isn't treated as suffix. This is Pandoc's fault, and apparently very intentional.

A workaround is to bracket the reference, i.e.
```markdown
@smith04 [cf. [@sec:introduction]]
```

Thankfully, pandoc-crossref doesn't differentiate between bracketed and non-bracketed references.
