### ISSUE TITLE
Book indexing with crossref?

### ISSUE THREAD

**Issue by puterleat** [lierdakil/pandoc-crossref#127]
Apologies if this isn't the right place to post, but this topic is somewhat hard to google because one of the key terms is 'index'!

I realise pandoc and crossref don't currently support anything like the Latex' `makeidx`, but I was wondering if anyone had build on crossref and filters to implement something similar?  I guess what I really want is the ability to add an attribute to a span which then becomes an item in a list (index) at the end of the book (I'm using bookdown). i.e. this would be an [index item]{.index} I don't personally need anything much more complex (e.g. `seealso` type features).

Any info much appreciated!

**Comment by lierdakil** [comment]
It's rather easy to write a filter that would iterate over spans and spit them out at the end, possibly hyperlinked. Problem is, you usually want to reference a page in index. That would be challenging to say the least, since Pandoc doesn't have any idea about pagination in most cases (which is unsurprising, considering most output formats have floating pagination!). Also no idea how to convince Bookdown to use a Pandoc filter.

**Comment by puterleat** [comment]
If the filter just covered to  \index tags for latex output perhaps that wouldn't matter? Hyperlinks would suffice for non paginated outputs and if you want page numbers could fall back to latex. 

I'll have a play with a filter. Feel free to close this issue.

**Comment by lierdakil** [comment]
Here's something to get you started, if you're up for some light Haskell action: https://gist.github.com/lierdakil/f4385e3957f39c8aa17b1ea478efb171
