### ISSUE TITLE
figureTitle doesn't work with PDF output

### ISSUE THREAD

**Issue by andresmrm** [lierdakil/pandoc-crossref#13]
Hi! Thanks for paddoc-crossref! =)

The config `figureTitle` works fine for HTML output. But it seems not to work with PDF output. I'm getting "Figure: ..." anyway.
Didn't set the Latex template, so it should be using Pandoc's default.
Tried setting `figureTemplate`, but made no difference neither.
Using: pandoc-crossref-0.1.0.2

**Comment by lierdakil** [comment]
Hi.

Sorry, this is not implemented as of yet, but LaTeX titles are customisable via pure latex, which can be embedded into source Markdown (and will be ignored in all outputs except LaTeX/PDF), f.ex. with default template, this will work (add this at the beginning of your Markdown document, after metadata block, and before any figures):
```latex
\renewcommand{\figurename}{Fig.}
```
I hope this workaround isn't too inconvenient for you.

Main problem with LaTeX is that there is a multitude of ways to specify figure titles, depending on packages used, etc, so there really is no silver bullet. That's why it's not implemented -- I haven't figured out yet how should I go about this to make it work for as many cases as possible.

I suggest leaving this issue open as a reminder and for posterity.

**Comment by andresmrm** [comment]
Wow! Worked like a charm!
Thanks again!

(Didn't know Pandoc ignored pure Latex in the other outputs, and was to lazzy
to create my own template)


Quoting Nikolay Yakimov (2015-05-06 21:24:23)

**Comment by lierdakil** [comment]
I have implemented rudimentary support for `figureTitle` and `tableTitle` with `\renewcommand*`. It works only for pdf/standalone output though, but I assume that's not a huge problem. Will probably publish to hackage before end of May.
