### ISSUE TITLE
Odd issue affecting Figure citations

### ISSUE THREAD

**Issue by OolonColoophid** [lierdakil/pandoc-crossref#133]
Hi there

A strange issue that I'm struggling to troubleshoot. As far as I'm aware, the below is not caused by a filter ordering issue.

In my document, I've got Figures, Tables and Equations. When I refer in the text to a nearby table, the label is correct, and when I click on the number in the PDF, I'm jumped to it. The same behaviour happens with equations. However, for figures, and only for figures, the figure number (which is correct beneath the figure itself) is replaced by the section within which the figure appears. Thus, if figure 1 is in section 4.2, I get:

> See Figure 4.2 

instead of the expected:

> See Figure 1

Obviously, the in-text citation is picking up the section for some reason.

Any ideas?

Cheers

Ian

**Comment by lierdakil** [comment]
Since you're mentioning PDF, I would guess you're using LaTeX output?

If my guess is correct, I would bet there's some dark magic going on inside your template. Outputting to LaTeX directly and troubleshooting that might be a helpful approach.

If you find no luck troubleshooting on your own, you could try to construct a minimal example and post it here, and I'll try to have a look.

**Comment by OolonColoophid** [comment]
Many thanks, lierdakil - I never actually got to the bottom of this one, but reconstructing the Latex template from scratch piece by piece worked!

**Comment by lierdakil** [comment]
Glad to hear that.
