### ISSUE TITLE
reference to code listings

### ISSUE THREAD

**Issue by arve0** [lierdakil/pandoc-crossref#16]
Currently I do:

<pre>
\begin{lstlisting}[language=Python, caption=Caption., label=code:label]
for file in files:
    ..do stuff
\end{lstlisting}
</pre>

Then I reference with `\ref{code:label}`. This gives me two syntaxes for referencing. It would be nice if `@code:label` would create `\ref{code:label}` regardless if pandoc-crossref finds a label named `code:label` in its own list of figures/equations/tables. Any ideas?

**Comment by lierdakil** [comment]
Creating a ref regardless would be *bad*, since pandoc-crossref piggybacks on citation syntax. That said, I might just straight up implement referencing fenced code blocks.

How is referencing code listings is supposed to work anyway? Never used it during my time with LaTeX, so I'm a little bit lost on how this should look when rendered.

**Comment by arve0** [comment]
There is two syntaxes used (as I'm aware of):
<pre>
```python
for i in range(10):
    print(10)
```
</pre>
and
<pre>
``` {caption="Caption.." label=mycode .python}
for i in range(10):
    print(10)
```
</pre>

This produces the output:
`pandoc code.md -o code.tex`:
```
\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{for} \NormalTok{i in }\DataTypeTok{range}\NormalTok{(}\DecValTok{10}\NormalTok{):}
    \DataTypeTok{print}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{for} \NormalTok{i in }\DataTypeTok{range}\NormalTok{(}\DecValTok{10}\NormalTok{):}
    \DataTypeTok{print}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}
```

Or with the listings package. `pandoc code.md --listings -o code.tex`:
```
\begin{lstlisting}[language=Python]
for i in range(10):
    print(10)
\end{lstlisting}

\begin{lstlisting}[language=Python, caption=Caption.., label=mycode]
for i in range(10):
    print(10)
\end{lstlisting}
```

**Comment by arve0** [comment]
And the rendered result:
![skjermbilde 2015-05-12 kl 22 54 28](https://cloud.githubusercontent.com/assets/4810521/7598354/046f4d60-f8fa-11e4-9717-8dca93202eee.png)
![skjermbilde 2015-05-12 kl 22 54 51](https://cloud.githubusercontent.com/assets/4810521/7598355/047245a6-f8fa-11e4-9619-b675055f8493.png)

As one can see, using listings package add caption and label support, but without listing package one gets color-highlighted code (which is nice).

**Comment by lierdakil** [comment]
Listings package is highly configurable, so it's possible to get nice colors with it, by using a custom LaTeX template. So from my perspective, I should primarily target `listings`-style output.

I'm wondering on how should I handle output formats other than LaTeX though, since pandoc doesn't presently support code block captions (https://github.com/jgm/pandoc/issues/673). One option would be to hack-in something resembling captions for the time being, of course (like a `div` with `listing-caption` class for example), but I wonder if there is a better option.

**Comment by lierdakil** [comment]
Anyway, I'll try to make something of it. Probably by the end of this week or so.

**Comment by arve0** [comment]
Great! :smile:

**Comment by lierdakil** [comment]
Sorry about the delay. I have implemented some semblance of what you requested. I'd be grateful if you could test 0.1.1.0 candidate to see if everything works fine.

You can install candidate with `cabal install http://hackage.haskell.org/package/pandoc-crossref-0.1.1.0/candidate/pandoc-crossref-0.1.1.0.tar.gz`

**Comment by lierdakil** [comment]
Check [Readme](https://github.com/lierdakil/pandoc-crossref#code-block-labels) to see what's implemented. Be mindful of metadata flags as well (`listings` and `codeBlockCaptions` in particular)

**Comment by arve0** [comment]
Referencing works (`[@lst:label]`), but I'm unable to get the caption to work. Have tried `Listing: Caption` above, `: Caption` below and with/without pandoc `--listings`.

**Comment by arve0** [comment]
Sorry, was not reading carefully. Had forgot `codeBlockCaptions`. Works nicely! Btw, `--listings` will give a nested listing, so the README should maybe note that.

Thanks!
