### ISSUE TITLE
Problem with referencing images

### ISSUE THREAD

**Issue by 089** [lierdakil/pandoc-crossref#166]
I have the following Problem with referencing images. If my markdown code was like 

> `![Caption.](test.png){#fig:test}`
> Lorem ipsum dolor sit amet, consectetur adipisici elit, sed `[Figure @fig:test]` tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea .

the image is **in front of the text**, has **no** caption and the **reference does not work** (==> `Figure ??`).

If there is a blank line between the image and the text like 

> `![Caption.](test.png){#fig:test}`
> 
> Lorem ipsum dolor sit amet, consectetur adipisici elit, sed `[Figure @fig:test]` tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea .

the image is **at the end of the chapter**, has **a caption** and the **reference does work** (==> `Figure ??`).

How can I combine both? Image within the text, working caption and reference. 

My command

~~~bash
	pandoc ${INPUTDIR}/*.md \
	-o ${OUTPUTDIR}/${DOCNAME}.pdf \
	-H ${STYLEDIR}/preamble.tex \
	--filter pandoc-crossref \
	--template=${STYLEDIR}/template.tex \
	--bibliography=${BIBFILE} \
	--csl=${STYLEDIR}/ref_format.csl \
	--highlight-style pygments \
	-V fontsize=12pt \
	-V papersize=a4paper \
	-V documentclass:report \
	-V lang:german \
	-V mainlang:german \
	-N \
	--latex-engine=xelatex
~~~

**Comment by lierdakil** [comment]
Pandoc-crossref only works for "figures". "Figures" are images with nonempty alt text that appear alone in a paragraph, see [Pandoc manual](http://pandoc.org/MANUAL.html#extension-implicit_figures)

The first case isn't considered a figure and is instead treated as an inline image, hence it isn't referenced and has no caption. This is by design.

Figure placement is controlled by LaTeX. If you want full control over where LaTeX places images, just use embedded LaTeX, there is no way to control that from Markdown (for one, because it doesn't make sense for any other output format). You can also look into making a custom LaTeX template with global placement options configured to your liking.
