### ISSUE TITLE
crossref running after citeproc breaks citations

### ISSUE THREAD

**Issue by memeplex** [lierdakil/pandoc-crossref#173]
Say this is the input (test.md):

```
---
bibliography: test.bib
---

Blah blah [@patas]
```

With bibliography (test.bib):

```
@misc{ patas,
       author = "Oren Patashnik",
       title = "BIBTEXing",
       year = "1988" }
```

Now run `pandoc --filter pandoc-citeproc --filter pandoc-crossref -t latex test.md` and you get

```
Blah blah {[}@patas{]}
```

But run `pandoc --filter pandoc-crossref --filter pandoc-citeproc -t latex test.md` instead and you get:

```
Blah blah (Patashnik 1988)
```

**Comment by lierdakil** [comment]
Did you read the manual? Almost the first thing in there: http://lierdakil.github.io/pandoc-crossref/#pandoc-citeproc-and-pandoc-crossref

**Comment by memeplex** [comment]
Sorry :( I've read it but it's now clear that I forgot about that part, I think I search for citeproc in the README before posting this.

**Comment by robwalton** [comment]
Hi @lierdakil, it doesn't look like this issue comes up very often, but it might be possible to add a check for this and report an error. The API for [Text-Pandoc-App](http://hackage.haskell.org/package/pandoc-2.1.3/docs/Text-Pandoc-App.html) shows that the `Opt` data structure includes a filed `optFilters` which holds a list of filters. This may be available to filters when they are run. Reading the docs also works!
