### ISSUE TITLE
Enable equation labels on separate line, to not break Typora live preview?

### ISSUE THREAD

**Issue by gandalfsaxe** [lierdakil/pandoc-crossref#183]
In [Typora](https://typora.io), the live preview of displaymath requires either
 ```latex
$$...$$
```
or
```latex
$$
...
$$
```

But it breaks if there is anything else on the line such as:
```latex
$$...$$ {#somelabel}
```
or
```latex
$$ {#somelabel}
...
$$
```

There is no problems with the table labels because they are defined on `pandoc-crossref` as being on a separate line. Have you considered doing the same for equation labels, at least in addition/optionally to the same-line labels, such that live previews in editors such as Typora doesn't break?

**Comment by gandalfsaxe** [comment]
I have also made an issue with Typora, we can wait and see what they respond first: https://github.com/typora/typora-issues/issues/1576

But it could perhaps still be a good idea to implement in any case, since the same issue could appear in other markdown editors.

**Comment by gandalfsaxe** [comment]
Ah it turns out this syntax actually worked, 

```markdown 
$$
...
$$ {#somelabel}

So I don't think any changes are needed. Unless anyone have something to add, you may close this :)

**Comment by gandalfsaxe** [comment]
No wait, it's actually as bad as I feared first. While the syntax above doesn't break the current equation preview, it does break the next:

Source without labels:
```markdown
Test 1:

$$
e=mc^2
$$

Test 2:
$$
e=mc^4
$$

Bla bla...
```

Typora live preview:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/12127864/41820266-4d24ef18-77cf-11e8-95a0-a406e1945c87.png">


Source with labels:
```markdown
Test 1:

$$
e=mc^2
$$ {#eq:test1}

Test 2:
$$
e=mc^4
$$ {#eq:test2}

Bla bla...

​	

```

Typora live preview:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/12127864/41820273-729b2604-77cf-11e8-8744-93798843b4a9.png">


Again, I know you have nothing to do with Typora. The point is, if you could support the equation tags could be one line above or below the displaymath environment (similar to table labels), this wouldn't be an issue! :)

**Comment by lierdakil** [comment]
The fact that it's breaking the *next* equation on Typora is definitely a bug they should address, I think.

As for the rest...

The reason for the chosen syntax is that in Pandoc both display and inline math are inline elements. So they can't have block-style labels, like tables and code blocks.

The syntax could be amended to support a *single* line break after an equation (since it's not a paragraph break, and it was supported in older versions actually, before Pandoc's AST made a distinction between spaces and line breaks), but more wouldn't be possible since then the equation itself and its label will be in different paragraphs, which is just silly and in most cases wouldn't be what the user intended in the first place.

**Comment by gandalfsaxe** [comment]
I don't know if it's a bug per se since it's clearly related to the way Typora interprets the ending `$$`. But I don't know how to understand the output either, so I agree it seems buggy. I agree that Typora should fix this, and I've made an issue with them, but I'm not sure they will.

I would *really* appreciate if you could expand the syntax to allow for an optional single line break between the _last_ `$$` and the labels. I.e. both of the should work:
```markdown
$$...$$
{@eq:somelabel}
```
and also
```markdown
$$
...
$$
{@eq:somelabel}
```

Definitely for equations, and for consistency you could apply it to figures too. It would completely solve all my current headaches! 👍

**Comment by lierdakil** [comment]
Image labels/attributes are parsed by Pandoc, so take that up with them, I can't do much about that and don't really want to.

**Comment by gandalfsaxe** [comment]
Ah ok, so when you said
> The syntax could be amended to support a single line break after an equation...

it (practically) has to be done in `pandoc`, not `pandoc-crossref`?

**Comment by lierdakil** [comment]
*Image* labels/attributes are handled by Pandoc. Pandoc-crossref offers a few (hacky) extensions on top of Pandoc Markdown -- math labels being one of those, with syntax chosen to be more or less in line with objects that can have labels in Pandoc Markdown (from the top of my head, sections and images).

So I *can* change how *math* labels work, because that's handled by pandoc-crossref. I *can't* (directly) affect how *image* and *section* (that is, header) labels work because that's handled by Pandoc itself.

P.S. I actually commited the change discussed here, if you didn't notice. Just FYI.

**Comment by gandalfsaxe** [comment]
Aah ok, gotcha. We're on the same page then.

Oh wow, you did? Fantastic! Apologies for being a noob, but how can I run this latest build? I don't suppose I can just run `cabal update` and `cabal install pandoc-crossref`, since there hasn't been a version bump since your commit?

**Comment by lierdakil** [comment]
Clone the repo and build it? If you're on Windows, I can pull the build artefact from CI.

**Comment by gandalfsaxe** [comment]
On mac. Ah so running `stack setup` + `stack build` worked, and your commit works perfect. Thanks a lot!

Side-question: I did have to add `export PATH="[PATH-TO-REPOS]/pandoc-crossref/.stack-work/install/x86_64-osx/nightly-2018-06-12/8.4.3/bin:$PATH"` to my bash profile. It feels a little heavy if one needs to do this for every manually build repo. Is there any smart solution to this, or is that just standard procedure to have a bunch of extra exports for own builds? :)

PS: When I tried to update via `cabal install`, the latest one it pulled down was pandoc-crossref-0.3.1.0, so quite old ;)

**Comment by lierdakil** [comment]
> Side-question: I did have to add export

`stack install`

> When I tried to update via cabal install, the latest one it pulled down was pandoc-crossref-0.3.1.0

`cabal update`. Also, IIRC, cabal-install will try the minimal-update strategy by default, i.e. keep pandoc, pandoc-citeproc, and their dependencies pinned and find the latest compatible pandoc-crossref version. Specify the version range if you want to force cabal-install to try to find a build-plan with more updates. Updating everything with cabal-install is a very arduous process with a lot of caveats, that's why sandboxing is strongly recommended when working with cabal-install -- that way, when everything else fails, you can just nuke the sandbox and start over -- which is definitely preferable to nuking *everything*.
