### ISSUE TITLE
Is full dependency on pandoc really needed?

### ISSUE THREAD

**Issue by jgm** [lierdakil/pandoc-crossref#193]
If pandoc-crossref only depended on pandoc-types, the executable would be much smaller.
Looks like you use:

```
lib/Text/Pandoc/CrossRef/References/Blocks.hs
28:import Text.Pandoc.Shared (stringify)

lib/Text/Pandoc/CrossRef/Util/Meta.hs
39:import Text.Pandoc.Shared hiding (capitalize)

lib/Text/Pandoc/CrossRef/Util/Util.hs
30:import Text.Pandoc.Class
35:import Text.Pandoc.Writers.LaTeX

src/ManData.hs
27:import qualified Text.Pandoc as P
30:import Text.Pandoc.Highlighting (pygments)
```

I'm not sure what is used from the unqualified imports, but `stringify` could easily be redefined, and `pygments` could be obtained from skylighting itself (if it's necessary at all -- avoiding skylighting would also be great).

**Comment by lierdakil** [comment]
LaTeX writer is used to correctly quote strings for LaTeX output. Markdown reader is used for reading YAML settings files (since some fields are Markdown text).

Markdown reader and some writers (HTML, TXT) are used in some TH trickery to embed manual into the executable. Pygments is used for passing it as HTML output highlighter.

Overall, it *could* be possible to remove the dependency on Pandoc itself, but that would lead to one hack being built on top of another hack, and I *really* don't want to do that, the code is hacky enough as is.

**Comment by jgm** [comment]
The part about embedding the manual could be avoided
by putting this in the build process. But I see the
issue about settings files and LaTeX strings. (I
suppose you could shell out to pandoc, though, instead
of building it in as a library?)

**Comment by lierdakil** [comment]
Shelling out would be a bit of a nightmare, especially on Windows.

**Comment by jgm** [comment]
OK, just thought I'd raise the possibility.
