### ISSUE TITLE
Installation fails on NixOS due to failing LaTex test

### ISSUE THREAD

**Issue by JonathanReeve** [lierdakil/pandoc-crossref#199]
Here's the error I'm seeing: 
```
Failures:

  test/test-pandoc-crossref.hs:290:25:
  1) LaTeX.Labels Tbl labels
       expected: "\\hypertarget{tbl:some_table1}{}\n\\begin{longtable}[]{@{}@{}}\n\\caption{\\label{tbl:some_table1}A table}\\tabularnewline\n\\toprule\n\\tabularnewline\n\\midrule\n\\endfirsthead\n\\toprule\n\\tabularnewline\n\\midrule\n\\endhead\n\\tabularnewline\n\\bottomrule\n\\end{longtable}\n\ntbl.~\\ref{tbl:some_table1}"
        but got: "\\hypertarget{tbl:some_table1}{}\n\\begin{longtable}[]{@{}@{}}\n\\caption{\\label{tbl:some_table1}A table}\\tabularnewline\n\\toprule\n\\endhead\n\\tabularnewline\n\\bottomrule\n\\end{longtable}\n\ntbl.~\\ref{tbl:some_table1}"
```
NixOS won't install packages that don't pass tests, so this failing test means that I can't install pandoc-crossref on my version of NixOS.

**Comment by lierdakil** [comment]
Upstream tends to change LaTeX output between minor releases, sometimes significantly. Aside from covering test code in conditionals on Pandoc's version (which I won't do for obvious reasons), or removing those tests altogether (which I also don't want to do because despite being flaky, they're useful), there's nothing I can do really.

**Comment by costrouc** [comment]
@lierdakil running into the same issue (also using nix for my dissertation).  What actions should we as a user do? Could we disable that test easily?

@JonathanReeve if you really need to use the package you can override it.

```
  pandoc-crossref-0321 = pkgs.haskell.lib.overrideCabal pkgs.haskellPackages.pandoc-crossref (oldAttrs: {
    doCheck = false;
  });
```

**Comment by JonathanReeve** [comment]
@costrouc, do you know how/where to add that to configuration.nix? I have [a list of `environment.systempackages`](https://github.com/JonathanReeve/dotfiles/blob/master/dotfiles/configuration.nix#L59) but I don't seem to be able to add expressions like that in my list.

**Comment by costrouc** [comment]
See this https://nixos.org/nixos/nix-pills/nixpkgs-overriding-packages.html#idm140737315541056

I am assuming that you are using NixOS. This just be a regular attribute in your configuration.nix

**Comment by lierdakil** [comment]
Hm. I'll see if I can hide flakier tests behind a flag, maybe.

In the meantime, using overrides to disable testing altogether is your best bet -- in most cases if the package's horribly broken due to dependencies changing, it just won't compile in the first place. Tests are meant more as a developer tool anyway (a "did I just break something" indicator), and don't necesserily tell something about pandoc-crossref itself.

**Comment by costrouc** [comment]
Thank you @lierdakil. I will disable the tests for the 0.3.2.1 release in nixpkgs. Nixpkgs uses tests to ensure that all modules behave as expected. I cannot speak for haskell packages but for python packages a package will often install but break due to a missing undeclared dependency (due to python's dynamic import). It is my understanding that haskell doesn't have this problem.

**Comment by costrouc** [comment]
I believe that this issue is resolved for now until at least the next release.

**Comment by lierdakil** [comment]
The "next release", that is, v0.3.3.0, is up, but it requires pandoc-2.3 though, which IIRC isn't in nixpkgs yet. Tests that could be flaky (almost half of those) are hidden behind a flag (disabled by default), which should hopefully be good enough once nixpkgs updates to pandoc-2.3.
