### ISSUE TITLE
NixOS build fails due to Pandoc dependency

### ISSUE THREAD

**Issue by JonathanReeve** [lierdakil/pandoc-crossref#201]
The NixOS build fails at the moment, due to a missing Pandoc dependency: 

```
Configuring pandoc-crossref-0.3.3.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
pandoc ==2.3.*
```

I don't know enough about Nix to really diagnose this, but maybe upgrading this dependency to pandoc 3.X would help, since that's the version available in the Nix repos?

**Comment by lierdakil** [comment]
Uh... there is no Pandoc 3.x? Latest released is Pandoc 2.3.1...

**Comment by lierdakil** [comment]
IIRC nixpkgs has Pandoc 2.2.1, so it's lagging behind for whatever reason. pandoc-crossref-0.3.2.1 is the last to support Pandoc 2.2. You could just install pandoc-crossref package from Nix repos. `nix-env -iA nixpkgs.haskellPackages.pandoc-crossref`

**Comment by lierdakil** [comment]
Ah, no, that won't work apparently since nix bumped pandoc-crossref for whatever reason. @costrouc you might want to take a quick look at this. I'm a bit fuzzy on the details of update policies in haskellPackages, but pretty sure since crossref-0.3.3.0 depends on pandoc-2.3.*, it *really* shouldn't have been updated.

**Comment by lierdakil** [comment]
Created an issue upstream https://github.com/NixOS/nixpkgs/issues/47872

**Comment by lierdakil** [comment]
In the meantime, something like this in `.config/nixpkgs/config.nix` should hopefully patch up things a bit:
```nix
{
  packageOverrides = pkgs: {
    haskellPackages =
      let orig = pkgs.haskellPackages; in
      orig // rec {
        pandoc-crossref = orig.pandoc-crossref.override {
          pandoc = pandoc_2_3;
        };
        pandoc_2_3 = orig.pandoc_2_3.override {
          haddock-library = orig.haddock-library_1_6_0;
        };
      };
  };
}
```

**Comment by JonathanReeve** [comment]
Right you are—I must've read the wrong version from somewhere. Thanks so much for looking into this. My papers stopped compiling with pandoc-crossref not building, and I don't have the nix skills to write overrides yet, myself. I'll use that patch. Feel free to close this issue, in favor of the one on nixpkgs.

**Comment by matthewbauer** [comment]
Pandoc 2.3.1 is not in lts-12.12 while 2.2.1 is:

https://www.stackage.org/lts-12.12/package/pandoc-2.2.1

Packages should maintain compatibility with Pandoc 2.2.x until lts-12.13 is released. Not a lot NixOS can do when packages break compatibility with LTS.

**Comment by lierdakil** [comment]
Oh come on, do you seriously expect that anyone will hold off releases because of a single distro that isn't that popular?

**Comment by matthewbauer** [comment]
Is it possible to support both versions of Pandoc? That would be what is done in for instance pandoc-citeproc:

http://hackage.haskell.org/package/pandoc-citeproc

It just becomes too much of a mess to ship every single version of Pandoc so we just do the latest LTS for each GHC version (or if it's not in LTS then the latest version in hackage). I don't know how other package managers do things but I would imagine it's similar. You can reproduce this behavior in stack with:

```
stack --resolver lts build
```

If you want a specific version of your package to go into LTS, then you can open an issue at:

https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package-to-an-lts-snapshot

which can for instance set your package at 2.2.x in LTS-12.x.

**Comment by lierdakil** [comment]
> Is it possible to support both versions of Pandoc?

Yes, but that's too much overhead for me. To politely return your own words back to you, "it just becomes too much of a mess"

> You can reproduce this behavior in stack with

There's a huge difference though. For one, stack actually verifies you can build all packages in a snapshot. nixpkgs currently ships pandoc-crossref version that does not build due to unsatisfied dependencies. Besides, you can build an older version with stack no problem. Just `stack --resolver lts build pandoc-crossref-0.3.2.1` (well, there is a caveat to that, because one dependency isn't in stackage, but you get the point). Nixpkgs only ships the latest version. Which can't be built.

> If you want a specific version of your package to go into LTS

I do not. I have more than enough on my plate as it is, and there is no reason to *want* to get pandoc-crossref into stackage in the first place.

My issue isn't that you don't ship every Pandoc version. My issue is that you're apparently ignoring hard version constraints set in the cabalfiles when bumping package versions in nixpkgs.haskellPackages and hope for the best. This is not a sane way to do this by any measure.

**Comment by matthewbauer** [comment]
Yeah, nixpkgs-unstable always uses the latest stable version of a package. There isn't any sort of constraint checking in the updates. This is what Stackage does really well. The good news is it will eventually update Pandoc to 2.3.0 and things will start working again. Not sure why they are waiting to bump it- most likely some other package is not compatible with 2.3.0 yet! If you aren't part of the Stackage LTS, though, your best bet is to make your constraint window as big as possible. Usually it is just a couple of tweaks to support multiple versions (not sure about how Pandoc works though).

Otherwise, users can use an older NixOS channel with pandoc-crossref.

```
nix-env -f channel:nixos-18.03 -iA haskellPackages.pandoc-crossref
```
