### ISSUE TITLE
anchors without captions

### ISSUE THREAD

**Issue by v217** [lierdakil/pandoc-crossref#218]
In many cases captions are redundant, if you just want numbering. So why are they not optional?

**Comment by lierdakil** [comment]
You'll have to explain your use-case. Not sure I follow.

**Comment by v217** [comment]
In some cases, I am happy with just numbering images, similar to equations, without captions. The reason being that I insert the images exactly in the textflow, where they should be, so a caption would be reundant. Nevertheless for referencing some of the images must be numbered.

**Comment by lierdakil** [comment]
You can use `figureTemplate` metadata variable to achieve this effect. Specifically,
```yaml
figureTemplate: $$i$$
```
will make it so that figure captions only consist of their ordinal number; setting it to empty string will suppress figure captions entirely; etc.

See http://lierdakil.github.io/pandoc-crossref/#item-title-templates and http://lierdakil.github.io/pandoc-crossref/#templates for more information.

**Comment by v217** [comment]
Ok, great. Thanks!
