### ISSUE TITLE
Equation numbering in MS Word

### ISSUE THREAD

**Issue by wolf-zchen** [lierdakil/pandoc-crossref#221]
Hi, I am a new pandoc user. I used pandoc-crossref as the filter to transfer from .tex to .docx. The resulting .docx file has correct figure numbering and the hyperlink also works fine. However, there is no numbering for the equations. 
For example, the \label{eq:1} is left as hyperlink of [eq:1] in the word file, and the hpyerlink seems to work, but the equations have no numbering. 
It would be great if you could help me with what might be the issue.

**Comment by lierdakil** [comment]
Okay, so long story short, pandoc-crossref doesn't really support any input formats besides Pandoc Markdown, mostly because any additional input format would require duplicating half the code, and frankly I'm struggling a bit with maintenance as it is. So the fact that *anything* works at all when converting from LaTeX is *definitely* not because pandoc-crossref did something.
