### ISSUE TITLE
support multi page code block

### ISSUE THREAD

**Issue by annProg** [lierdakil/pandoc-crossref#228]
Since floats cannot be broken across pages，long code block with `pandoc-crossref` will overflow.
So , may add a class to code block, such as `.long`, when read this class, use `capt-of` to add caption. Otherwise use `float`

~~~markdown
```{#lst:test .md .long caption="Test Multi Page Code"}
# Test
## Test
```
~~~

ref: https://tex.stackexchange.com/questions/175650/how-to-allow-page-break-inside-a-float-environment

**Comment by lierdakil** [comment]
Overly long code listings don't really work all that well as "something with caption", since the caption will generally end up on a different page from the object itself. Perhaps a better idea would be to put the code in question into some sort of supplementary section, and reference that section instead? At least, that's what I would've done in this case.

If you absolutely _have_ to use floats, you have two options:

1. Using `listings` package -- invoke pandoc with `--listings -Mlistings` command line arguments.
2. Using raw LaTeX. Also, see https://tex.stackexchange.com/questions/117836/code-listing-spanning-multiple-pages-with-captions-at-top for an idea about a more meaningful formatting.

I'm currently trying to get away from treating LaTeX specially in pandoc-crossref. The reason being, if you're only targeting LaTeX, it makes more sense to just use LaTeX, without pandoc/pandoc-crossref as a middleware. And when targeting multiple output formats, having LaTeX treated specially leads to all kinds of inconsistencies in the outputs. So I probably won't try to implement "long code blocks" anytime soon.

Sorry it took me a while to answer.

**Comment by annProg** [comment]
Thanks. Now I am using codeblock without caption to write long code
