### ISSUE TITLE
Feature Request: Reference without link

### ISSUE THREAD

**Issue by jokorn** [lierdakil/pandoc-crossref#23]
Thank you for a great package - works great!
Is it possible to create references in text without the link? Either for the entire document or on a per reference basis.
I tried redefining the \ref to use \ref* in the metadata of my file but couldn't make it work. I then tried hiding the links with \hypersetup[hidelinks] - this hid the links but broke my custom "figureTitle" and "figPrefix" (by the way, I can never make "titleDelimiter" work).
I was thinking that, selective suppression might be accomplished by using /ref* instead of /ref when the reference is called with a "-" before the reference like this "-@fig:figure1". This syntax is similar to "pandoc-citeproc" where "-@citekey" suppresses mention of the author in the citation. Unfortunately, I don't have the coding skills to contribute to the this.
And again, thank you for the great work on this package!

**Comment by lierdakil** [comment]
`titleDelimiter` doesn't work with LaTeX output atm. Metadata options are less flexible with LaTeX in general. I should probably document that.

As for the rest, I think `\hypersetup[hidelinks]` shouldn't interfere with title/prefix, if done correctly. Apparently, there is a little bug which requires `header-includes` metadata field to be a YAML array, otherwise it doesn't add custom settings to it. That will be fixed in next release. For now, you can use something like this in your metadata block:
```yaml
header-includes:
    - "\\hypersetup[hidelinks]"
```

Since references are managed by LaTeX, I think that hyperlinks should also be controlled by LaTeX, so frankly, I think that inventing something for this is out of scope.

**Comment by lierdakil** [comment]
Ok, updated readme with some information on LaTeX:
https://github.com/lierdakil/pandoc-crossref#latex-customization

**Comment by jokorn** [comment]
Thank you for the quick answer. Adding \hypersetup{hidelinks} as a YAML-array solved it - it doesn't break the custom figureTitle and figPrefix anymore. 
And the clarification in the readme really helps.
If I want need to completely remove the links I'll either create a custom "header-includes" (I have to work on this) or I'll create an intermediary tex-file and do a "search-and-replace" - one of those should work.
Again thanks for the response and the great work!
