### ISSUE TITLE
How to get exe file for windows

### ISSUE THREAD

**Issue by danil-tolkachev** [lierdakil/pandoc-crossref#24]
Hello! Sorry for my question, but I don't know Haskell. 
I want to get standalone executable file for pandoc-crossref and run it in portable way on machines where no Haskell distributive. How can I do this?

**Comment by lierdakil** [comment]
Sorry, there's no way to get completely standalone executable, at least not that I know of. What you can do is bundle required libraries with pandoc-crossref: if you place those in the same directory as executable, Windows should be able to find those (just run pandoc-crossref with PATH unset and you should get an idea of what's missing)

That said, I'm not much of a Windows guy, so I might be wrong.

**Comment by danil-tolkachev** [comment]
My answer to my question. May be it is usefull for beginners in Haskell. 

To get an executable file on Windows, it is necessary to perform actions:
- Download and install [Haskell Platform for Windows](https://www.haskell.org/platform/windows.html)
- Launch cmd as Admin

Execute commands:
  `cabal install cabal-install --global`
  `cabal update`
  `cabal install pandoc-crossref`

In the directory `%AppData%\cabal\bin\` will be needed `pandoc-crossref.exe`

**Comment by avonmoll** [comment]
I'm interested in this as well. I am wanting to use pandoc-crossref on a work PC where I don't have admin privilages and cannot install Haskell.

>  What you can do is bundle required libraries with pandoc-crossref

1. Is there somewhere to get the binary for pandoc-crossref in the first place?
2. What are the required libraries for pandoc-crossref?

**Comment by lierdakil** [comment]
@avonmoll get [stack](https://www.stackage.org/). Download one of (later) releases. Unpack. Run `stack install` in unpacked directory (one containing `stack.yaml`). You'll eventually get `pandoc` and `pandoc-crossref` executables somewhere on your system (read command output to learn where exactly, I'm not entirely sure). While at it, you might also want to `stack install pandoc-citeproc`. You can do this without administrator privileges.

As for libraries, you probably will need msys2 libraries (but don't quote me on that). Those *should* be fetched by stack automatically, by the way. If you want to get those manually, probably [20150512 base package](https://sourceforge.net/projects/msys2/files/Base/i686/msys2-base-i686-20150512.tar.xz/download) will do it. Likely any dll you'll need will be under `msys32/usr/bin` in that archive.

This is all untested, and I didn't touch Windows in a while. So good luck I guess?

P.S. If this all sounds overly complicated, sorry about that. You might try [prebuilt executable](https://ci.appveyor.com/api/buildjobs/58hikctpjitq98e8/artifacts/pandoc-crossref.exe), but I have no idea if it will work or what it will require. Make sure you're using pandoc 1.16.0.2 though, since it definitely won't work with earlier versions.

**Comment by avonmoll** [comment]
It looks like I've gotten stuck in the complicated route (get stack -> run `stack install`) because I have a missing tool (`msys2`). I tried `stack install pandoc-crossref` and it failed trying to build a particular package it requires a Unix compatibility toolchain (such as MinGW+MSYS or Cygwin).

The prebuilt executable appears to be working properly, however. The following MWE is building properly from the command line:
mwe.md
```
---
title: Some Title
subtitle: Some Subtitle
author: Me
date: today
...

# MWE

![testing a figure](\path\to\image.jpg){#fig:myfigure}

Above is @fig:myfigure.
```
Using `pandoc --filter=pandoc-crossref --filter=pandoc-citeproc --smart --listings --number-sections --standalone mwe.md -o mwe.pdf`

__HOWEVER__, I am using Atom along with markdown-preview-plus with Pandoc enabled and it appears that it is not calling pandoc-crossref. Using the same options as above, the preview pane shows: `Pandoc Error: pandoc-citeproc: reference fig:myfigure not found`. This doesn't appear to be an issue with pandoc-crossref, but I was wondering if you might have some insight.
