### ISSUE TITLE
long listings with pandoc-crossref doesn't fit on page (originally by Everettss)

### ISSUE THREAD

**Issue by GH-TpaeFawzen** [lierdakil/pandoc-crossref#243]
[Originally asked in StackExchange](https://tex.stackexchange.com/questions/472363/long-listings-with-pandoc-crossref-doesnt-fit-on-page)

**Comment by lierdakil** [comment]
With LaTeX output, listings, as well as every other object pandoc-crossref is aware of, are put into floats, as per usual practice. And since you've opted to talk via links to StackExchange, I feel justified to answer in kind, so https://tex.stackexchange.com/questions/147512/latex-a-single-code-listing-over-multiple-pages

FWIW, you can make your own LaTeX template where you could define `codelisting` environment to be literally anything you want. See [pandoc manual](https://pandoc.org/MANUAL.html#templates) for details
