### ISSUE TITLE
inconsistent duplicate id error.

### ISSUE THREAD

**Issue by Zoefschildpad** [lierdakil/pandoc-crossref#246]
I have two files with code blocks. Both have code blocks with the same id, the only difference is that the first has 2, and the second has 3 copies. When I run the command `pandoc <file> --filter=/opt/pandoc-crossref -t html` the first converts and the second gives a duplicate id error. Is there a reason this is inconsistent or is this a bug? 
[test1.txt](https://github.com/lierdakil/pandoc-crossref/files/4214898/test1.txt)
[test2.txt](https://github.com/lierdakil/pandoc-crossref/files/4214891/test2.txt)

**Comment by lierdakil** [comment]
That's a bug all right. But not an issue in logic (not that I can see anyway). I'm either tripped up by the non-strict evaluation somewhere, or perhaps there's a subtle bug in GHC 8.6.5. I'll try to investigate and get back to you.

**Comment by lierdakil** [comment]
Yeah, okay, the issue here is non-strict evaluation of state that tracks references.

Long story short, unless something forces the evaluation of state, the code that checks for duplicate labels is never executed at all. I'm guessing that at three items, the runtime decides that building up unevaluated thunks is more expensive than doing the evaluation and runs the code.

Note that if you _reference_ the duplicate item, this forces state evaluation and you get an error.

Manually forcing the state value to at least WHNF resolves the inconsistency. I'll try to push out a correcting release this week.
