### ISSUE TITLE
windows i386 release

### ISSUE THREAD

**Issue by Jianchun1** [lierdakil/pandoc-crossref#248]
hi，would you like to add a release for windows i386 platform? It will help those people who are still working on old machines.

Thanks in advance.

**Comment by lierdakil** [comment]
Huh. I could swear I've answered this, but apparently not.

So, in a nutshell, I'd be happy to, but since I'm building on AppVeyor, which only provides x86_64 hosts, this is a bit of a pain to set up. I won't have much spare time at least until summer, so if someone can look into either whether GitHub Actions provides 32-bit hosts or how to set up 32-bit Haskell compilation on AppVeyor (https://gitlab.haskell.org/ghc/ghc/wikis/building/compiling32on64 is probably the place to start with that), that would be helpful.

**Comment by lierdakil** [comment]
Microsoft drops 32-bit support. GHC drops 32-bit Windows support. This is pretty much a non-starter at this point.
