### ISSUE TITLE
pandoc-crossref / pandoc version check and message

### ISSUE THREAD

**Issue by wlupton** [lierdakil/pandoc-crossref#253]
I've been getting this for the last few weeks (because the homebrew pandoc version was ahead of the pandoc-crossref version) but I wonder whether the message is appropriate for minor version number increments, and/or whether there could be a metadata variable to control it?

```
WARNING: pandoc-crossref was compiled with pandoc 2.9.2 but is being run through 2.9.2.1.
This is not supported. Strange things may (and likely will) happen silently.
```

**Comment by lierdakil** [comment]
See, the issue is, pandoc does sometimes change behaviour between minor or on occasion even patch releases. It follows the [Haskell PvP](https://pvp.haskell.org/), which doesn't necessarily constrain the behaviour, like semver does, but the API. So I think this warning is useful in any case. Whether or not there are indeed issues, will vary from instance to instance.

As a side note, if pandoc makes drastic changes, which generally happens between major versions, pandoc-crossref will most likely just refuse to work at all. So the warning is the most useful with minor and patch releases. (note that Haskell PvP specifies first _two_ components as a major version, i.e. 2.9 is the current _major_ version of pandoc)

The primary reason why there might be subtle bugs if versions don't match is that pandoc-crossref reuses parts of pandoc, and those parts are compiled in. So issues may arise from subtle inconsistencies in behaviour between the compiled-in and "external" versions of pandoc.

FWIW, the new build was released yesterday: https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.2a

There is no metadata variable to control this warning. I don't see much merit in such an option, frankly. If you _have_ to silence this warning, you can run pandoc-crossref in "pipe mode", i.e. `pandoc -t json file.md | pandoc-crossref --pipe html | pandoc -f json -t html -o output.html`, but this is reserved for tinkerers, mostly, so generally not recommended.

**Comment by wlupton** [comment]
Thanks. I guess in this case it was slightly annoying because there was a relatively long lag between the new pandoc version and the updated pandoc-crossref version :(.

I'm dependent on homebrew, and I expect that the new pandoc-crossref version will show up soon. Having updated pandoc via homebrew, I couldn't see a way of downgrading it again (I tried the @n.m syntax but no previous versions seemed to be available). If I could have downgraded, I would have done. This isn't your problem of course!

If I _did_ need to suppress the warning, I think I'd more likely grep -v it out!

Thanks particularly for the versioning information. It makes me think that I should be a bit more careful in my lua filters and custom writers!

OK (as far as I'm concerned) to close this issue.

**Comment by lierdakil** [comment]
Feel free to open issues here in case a new pandoc version is out and a matching pandoc-crossef version is not. I try to be more or less on top of this, but sometimes life gets in the way and I miss the release announcement or simply forget to set up a new build.

**Comment by wlupton** [comment]
Thanks. Good to know that you don't mind!

**Comment by dzackgarza** [comment]
If compiling from this repository, is there a way to attempt to compile pandoc-crossref with other versions of pandoc? For example, `pandoc -v` returns 2.9.2.1 whereas `pandoc-crossref -v` shows "Built with pandoc 2.9.1.1". 

I've tried setting pandoc==2.9.2.1 in the package.yaml file and running `stack install` from a fresh clone, but run into the same results.

(I ask because I'm currently only getting "??" for references, although this might be a separate problem.)

**Comment by lierdakil** [comment]
@dzackgarza, sorry, I kinda forgot to update `stack.yaml`. The reason you're seeing pandoc-2.9.1.1 here is that the current resolver doesn't have pandoc-2.9.2.1. I've bumped the resolver to current nighlty in `master`, try pulling and rebuilding.

Side note, if you want to build with a specific pandoc version, not necessarily the latest, probably easier to build with cabal-install than stack.
