### ISSUE TITLE
some issues regarding equation numbering and reference

### ISSUE THREAD

**Issue by ctex77** [lierdakil/pandoc-crossref#256]
Consider the following minimum document tmp.Rmd:

- - -
eqnPrefix: AB
tableEqns: true
- - -

$$x+y=1$${#eq:eq01}

The equation [@eq:eq01]

I compile it with the shell command "pandoc -Fpandoc-crossref tmp.Rmd -o tmp.tex".  Not as expected for a `\label{eq:eq01}` in numbering the equaiton, it is still a `\\qquad(1)` inside the math environment of equation in the TeX output tmp.tex.(I want the equation numbering to be right aligned, not some space after equation aligned center) And not as expected for `AB 1` in reference of the equation, it is `eq. 1`.

So could I ask about the correct way to set the two options of tableEqns and eqnPrefix?

The following two lines of 

eqnPrefix: AB
tableEqns: true

is the YAML setting, and should be surrounded by two lines of ---, which however shows as two horizontal lines here.

**Comment by lierdakil** [comment]
`tableEqns` is ignored when output is LaTeX IIRC, mostly because it's ugly and there's a better way in LaTeX anyway (i.e. `equation` environment with `\label`)

`eqnPrefix` should work though. I've tested it, and at least on current versions of pandoc and pandoc-crossref everything seems to work as expected:
```
[:~] $ cat /tmp/test.Rmd
---
eqnPrefix: AB
...

$$x+y=1$${#eq:eq01}

The equation [@eq:eq01]
[:~] $ pandoc -Fpandoc-crossref /tmp/test.Rmd -fmarkdown -tlatex
\begin{equation}x+y=1\label{eq:eq01}\end{equation}

The equation AB~\ref{eq:eq01}
[:~] $ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.4
// ...
[:~] $ pandoc-crossref --version
pandoc-crossref v0.3.6.2 git commit UNKNOWN (UNKNOWN) built with Pandoc v2.9.2.1, pandoc-types v1.20 and GHC 8.6.5
```

Note that if you're using v0.4.0.0-alpha then metadata format was changed a lot, and it doesn't handle LaTeX particularly gracefully (at least not yet), so you're probably better off with v0.3.x

**Comment by ctex77** [comment]
Thank you very much, lierdakil.

I think the key for my issue at this time lies in the version of pandoc-crossref. It works fine with 0.3.6.2. Either the code of

pandoc -Fpandoc-crossref test.Rmd -o test.tex
pandoc -Fpandoc-crossref test.Rmd -o test.pdf
pandoc -Fpandoc-crossref test.Rmd -o test.docx

produces output as expected which aligns equation number in the righ margin, and turns the referene caption of equation number from eq. to AB. For the DocX output, both the equation and its number are contained in a table. It is acceptible from my perspective given the equation number is right aligned. There is of course a warning as

WARNING: pandoc-crossref was compiled with pandoc 2.9.2 but is being run through 2.9.2.1. This is not supported. Strange things may (and likely will) happen silently.

which may be as you anticipate.

I tried another way before your comment yesterday. I combined the filter of pandoc-eqnos and pandoc-crossref (v0.4.0.0-alpha) by

pandoc -Fpandoc-eqnos -Fpandoc-crossref test.Rmd -o test.tex
pandoc -Fpandoc-eqnos -Fpandoc-crossref test.Rmd -o test.docx

The TeX output was as expected for equation number aligned at right with a \label inside an equation environment, but the DocX output was not and still aligned equation number at center akin to TeX effect with \\qquad inside math enviornment. 

Is it possible to keep this property of tableEqns of version 0.3x in future version? It is perhaps a customary to aligh equation number in right margin.

**Comment by lierdakil** [comment]
Not sure where you get your binaries, but pandoc-crossref v0.3.6.2 built with pandoc 2.9.2.1 is [available on the releases page](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.2a), and you wouldn't run into this problem if you compiled from source.

v0.4 is still very much a work in progress (hence the alpha label). `tableEqns` isn't in the v0.4 because v0.4 uses a more powerful templating approach, and I didn't yet add shortcuts for common use cases, as the format is still somewhat in flux.

**Comment by ctex77** [comment]
Thanks @malshar and @lierdakil. I also encountered the same problem like @malshar and opted to put up with it. @lierdakil 's suggestion really works.
