### ISSUE TITLE
Callback settings for Latex Macros

### ISSUE THREAD

**Issue by gabyx** [lierdakil/pandoc-crossref#261]
Is there any chance I can produce instead of 

```latex
\hypertarget{fig:figure0}{%
\begin{figure}
\centering
\includegraphics{img1.jpg}
\caption{A figure}\label{fig:figure0}
\end{figure}
}
```
the call to a makro call

```latex
\callbackImage{fig:figure}{img1.jpg}{key=valuem,key=value....}
```
otherwise this filter seems to be a bit intrusive as we cannot control the output of the output latex or is this possible by appending another custom-written pandoc filter ? 
Thanks for this project. If it would be in python I could understand it :-)

**Comment by lierdakil** [comment]
Long story short, pandoc-crossref doesn't actually produce LaTeX code for figures*. This is what pandoc is supposed to do. And no, there is no way to micromanage how pandoc's LaTeX writer works.

(* pandoc-crossref does produce LaTeX code for subfigures, but that's a giant hack, which I really would like to get rid of, but can't, because backwards compatibility)

You can write a custom filter, which you'd need to run after pandoc-crossref, which would replace figure elements by raw LaTeX of your choice, but that won't work with pandoc-crossref's subfigures (which are a giant hack basically)

But honestly, if you want to fiddle with LaTeX, why not just, you know, use LaTeX to begin with? You can also use raw LaTeX in Pandoc Markdown when targeting LaTeX exclusively.

> If it would be in python I could understand it :-)

For a Python equivalent of pandoc-crossref, check out https://github.com/tomduck/pandoc-xnos. Bear in mind, there's only some feature overlap and syntax is not generally compatible.

**Comment by gabyx** [comment]
Thanks for the short summary!
What I dont understand :-) and try to find out is:
how is then this fancy `\label{fig:blabla` represented in the AST of pandoc?

**Comment by gabyx** [comment]
The mentioned project `pandoc-xnos` is a bit out of date. I will try to use your library! :+1:

**Comment by gabyx** [comment]
I am targeting html and latex
https://github.com/gabyx/TechnicalMarkdown
