### ISSUE TITLE
caption setup problem in 0.4.0.0

### ISSUE THREAD

**Issue by zwz** [lierdakil/pandoc-crossref#266]
I find something new in the output of pandoc-crossref:
```
\@ifpackageloaded{caption}{\captionsetup{labelformat=empty}}{\usepackage[labelformat=empty]{caption}}
```
It overwrites the setup in the documentclass file (that is something like `Figure 1-2`), which works in 0.3.x version.

**Comment by lierdakil** [comment]
This is by design. v0.4 treats LaTeX as any other output format, i.e. doesn't offload cross-references to LaTeX. Hence, the caption suppression.

The reason for this change, it's virtually impossible to support the extensive prefix customization introduced in v0.4 using LaTeX macros without basically rewriting 3/4 of pandoc-crossref in LaTeX which I can't be bothered to do.

**Comment by zwz** [comment]
So there will be some significant changes in the document, and the caption setup (e.g. `Figure 1-2`) is still possible for the latex format (but maybe in another way) for v0.4, right?

**Comment by lierdakil** [comment]
Not sure I understand the question, but probably yes?

Markdown document
```markdown
---
defaultOption:
- numberSections
- chapters
captionIndexTemplate: '$$s.i%-$$$$ri$$'
prefixes:
  sec:
    captionIndexTemplate: '$$s.i%.$$$$ri$$'
---

A chapter {#sec:ch1}
=========

A section {#sec:sec1}
---------

![Some figure](img.jpg){#fig:fig1}

@sec:ch1

@sec:sec1

@fig:fig1
```

produces
![image](https://user-images.githubusercontent.com/7275622/85195819-52365e00-b2de-11ea-8664-c58b64ee5284.png)

This is all extensively customizable, but the details are mostly undocumented yet.

**Comment by zwz** [comment]
OK, I see. 
Now I switch back to v0.3.x, and look forward to the well-documented new version.
