### ISSUE TITLE
pdf, latex and Equations links

### ISSUE THREAD

**Issue by sajozsattila** [lierdakil/pandoc-crossref#270]
Hello,

I think there is a problem with the PDF generation. I can not link to Equations, but I can to Tables and Figure.

Example:

$$ P_\omega=2+{n_\omega\over 2}\hbar\omega\,{1+R\over 1-v^2}\int\limits_{-1}^{1}dx\,(x-v)|x-v| $${#eq:eqn1}

This link not working in PDF and LaTeX: [integrals](#eq:eqn1)

However the very similar for table yes:

| 1 | 2 |
| ------ | ----------- |
| 3| 4|
| 5| 6 |
Table: Demonstration of a simple table with caption and anchor {#tbl:1}

This is working: [table](#tbl:1)

The command which I have used:
`pandoc pdf.md -f markdown -t pdf --pdf-engine=xelatex -F pandoc-crossref -F pandoc-citeproc -o test.pdf`

I have attached some test Markdown file and the generated output:

[pdf.md.gz](https://github.com/lierdakil/pandoc-crossref/files/4859060/pdf.md.gz)
[test.pdf](https://github.com/lierdakil/pandoc-crossref/files/4859061/test.pdf)

**Comment by lierdakil** [comment]
Okay, pandoc-crossref doesn't create a hypertarget for equations if output format is LaTeX. Not necessarily a "problem", since this was originally intended this way, but I can see that this is not consistent with other output formats.

The idea was to rely on the magicks of hyperref package, and it is possible still. The caveat is you need to use `\hyperref` command instead of `\hyperlink` which Pandoc creates for links.

A stopgap measure would be to add something like this to `header-includes` or template preamble:
```
\makeatletter
\let\@@oldhyperlink\hyperlink
\renewcommand\hyperlink[2]{%
\ifcsname r@#1\endcsname%
\hyperref[#1]{#2}%
\else%
\@@oldhyperlink{#1}{#2}%
\fi }
\makeatother
```
which will redefine `\hyperlink` to contextually use `\hyperref` for any defined `\label`s and normal `\hyperlink` otherwise.

Meanwhile, I will try to figure something out wrt creating hypertargets.

**Comment by lierdakil** [comment]
I've released v0.3.6.4, which should add `\hypertarget` around equations.

**Comment by sajozsattila** [comment]
Thanks, you are very helpful

**Comment by sajozsattila** [comment]
I can confirm it is working, so I am closing the ticket
