### ISSUE TITLE
Doesn't work in R markdown

### ISSUE THREAD

**Issue by paniash** [lierdakil/pandoc-crossref#273]
Pardon me if someone has already asked this but is `pandoc-crossref` supported in R markdown? `pandoc-citeproc` works perfectly and I was wondering if another filter like `pandoc-crossref` would also work. I have tried it and it doesn't seem to. I was wondering if this is present in the software by itself or would I have to specifically configure R markdown to make `pandoc-crossref` work.

Thanks!

**Comment by lierdakil** [comment]
Hi. I don't personally use R, so I don't know, but people are using pandoc-crossref with Rmd, knitr, bookdown.

The basic idea is you need to tell pandoc to use pandoc-crossref. For that you need to pass it `--filter pandoc-crossref` argument. This argument _must_ be passed _before_ `--filter pandoc-citeproc` because crossref steals citeproc's syntax (hence applying citeproc first will break stuff since citeproc isn't aware of crossref).

**Comment by paniash** [comment]
Thanks, I'll try that out :)
