### ISSUE TITLE
Extra spaces just after a displayed math

### ISSUE THREAD

**Issue by masuday** [lierdakil/pandoc-crossref#275]
EDIT: I rewrote the issue with a suggestion.

### Markdown document
Using pandoc 2.9.2.1 (pandoc-crossref 0.3.6.4) or later, when converting the following Markdown to PDF or LaTeX,
```md
This is a test for equation numbering.
$$
y = a + bx + e
$$ {#eq:equation}
It will have an unnecessary space at the top of this line.

This is the second paragraph.
```

### Output

The output has an extra space at the top of line just after the displayed math.
![image](https://user-images.githubusercontent.com/6868817/90449007-85198a00-e0b4-11ea-95b5-b0be13c1f655.png)

The corresponding LaTeX source is as follows.
```latex
This is a test for equation numbering.
\protect\hypertarget{eq:equation}{}{\begin{equation}
y = a + bx + e
\label{eq:equation}\end{equation}} It will have an unnecessary space at
the top of this line.
```

Using pandoc 2.9.2.1 (with the previous version pandoc-crossref 0.3.6.3) yields the following output.
```latex
This is a test for equation numbering. \begin{equation}
y = a + bx + e
\label{eq:equation}\end{equation} It will have an unnecessary space at
the top of this line.
```

### Issues and suggestion
It should be because of #270. `\hypertarget` changes a block structure to a box in a paragraph, and the layout breaks. My suggestion is to insert `\hypertarget` inside the environment.

```latex
\begin{equation}\protect\hypertarget{eq:equation}{}{
y = a + bx + e
\label{eq:equation}}\end{equation} It will have an unnecessary space at
the top of this line.
```
It works and does not change the previous behavior. I appreciate it if you could fix this issue. Thank you.

**Comment by lierdakil** [comment]
This isn't something pandoc-crossref does, and furthermore 2.9.2.1 yields exactly the same output sans `\hypertarget`, so I have no idea what you mean by "source of issues".

Pandoc translates soft breaks (i.e. non-paragraph-starting newlines) into spaces or newlines in LaTeX as it sees fit. You have a soft break after the equation in source Markdown. It's not surprising that it's translated into a space.

Furthermore, since equations are typeset with paragraph breaks in LaTeX, this space should be entirely superfluous, i.e. shouldn't affect LaTeX output in any meaningful way.

If you _really_ want to get rid of that space for some reason, you can use the bracketed span syntax instead of the shorthand:

```markdown
[$$y = a + bx + e$$]{#eq:equation}It will NOT have a space between equation and this sentence
(because there is no space/soft-break in the source)
```

**Comment by masuday** [comment]
Thank you for your explanation. Yes, my "source of issue" is unclear, and I rewrote the original post.

Briefly, the current behavior breaks the layout just after `\end{equation}`. To keep the old behavior and the new feature, `\hypertarget` can be inside the environment, not enclosing the entire environment.

```latex
% current output
\protect\hypertarget{eq:equation}{}{\begin{equation}
y = a + bx + e
\label{eq:equation}\end{equation}} It will have an unnecessary space at
the top of this line.

% suggestion
\begin{equation}\protect\hypertarget{eq:equation}{}{
y = a + bx + e
\label{eq:equation}}\end{equation} It will have an unnecessary space at
the top of this line.
```

**Comment by lierdakil** [comment]
So, here's the problem: `hypertarget` part is added by pandoc, while everything from `\begin{equation}` and `\end{equation}` is handled by pandoc-crossref. While it's technically possible to write `\hypertarget` part by hand, I'd really like to avoid that, because if upstream changes how they do it, the change won't trickle down, so that's another thing to track, and frankly I already have my hands kinda full.

What I'm trying to say, it's not particularly straightforward fix. I'm currently pretty distracted by life stuff, so I'll think what I can do here, but it might take a while. In the meantime, suggestions are welcome. Also pull requests, although if you make one, try to avoid explicit raw LaTeX `\hypertarget`, because I will complain about that. From the top of my head, interleaving `RawInline`s with `Span` might work.

**Comment by lierdakil** [comment]
I've suddenly got myself some free time, so was able to fix this sooner than expected. Released as v0.3.8.0

**Comment by masuday** [comment]
I really appreciate your work to fix this issue quickly. I confirmed that there is no problem for the LaTeX (and pdf) with the latest release. It saves me a lot! Again, thank you for your effort.

**Comment by masuday** [comment]
Sorry, again. I found a really unfortunate problem.

The new release is perfect when the equation is in the environment between `\begin{equation}` and `\end{equation}`. Somehow, occasionally, the equation is surrounded by `\[` and `\]`, and unfortunately, the problem gets worse; the equation number disappears. 

The Markdown source is:
```md
This is the equation.
$$
\mathbf{A}^{-1}=\mathbf{B}^{-1}-\mathbf{C}^{-}.
$$ {#eq:label1}
The equation is (@eq:label1).
This is the issue:
$$
y=f(x).
$$ {#eq:label2}
The equation is (@eq:label2).
```

Its output is:
```tex
This is the equation. \begin{equation}\protect\hypertarget{eq:label1}{}{
\mathbf{A}_{22}^{-1}=\mathbf{A}^{22}-\mathbf{A}^{21}(\mathbf{A}^{11})^{-1}\mathbf{A}^{12}.
}\label{eq:label1}\end{equation} The equation is (eq.~\ref{eq:label1}).
The safer version is \protect\hypertarget{eq:label2}{}{\[
y=f(x).
\]} The equation is (eq.~\ref{eq:label2}).
```

The pdf output:
![image](https://user-images.githubusercontent.com/6868817/92061303-e94e7600-ed63-11ea-9abd-43d2db61ac93.png)

**Comment by lierdakil** [comment]
In the future, better create a new issue, less probable I miss it that way. I think I know what the problem is, I'll try to push out a patch in a day or two. Sorry.

**Comment by masuday** [comment]
Oh, I should have opened a new issue. Thank you for your comment.
