### ISSUE TITLE
Using pandoc-crossref with diagram-generator lua-filter

### ISSUE THREAD

**Issue by ctsa** [lierdakil/pandoc-crossref#282]
Hi, I'm trying to understand if a figure reference can be attached to a figure which has been added by an filter upstream of pandoc-crossref, for instance if I'm using diagram-generator (https://github.com/pandoc/lua-filters/tree/master/diagram-generator), with a diagram block such as: 

~~~~~~~~~~~~~~~~
```{.plantuml caption="This is an image, created by **PlantUML**."}
@startuml
Alice -> Bob: Authentication Request Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request Alice <-- Bob: another Response
@enduml
```
~~~~~~~~~~~~~~~~

...would it be possible to refer to this figure?

**Comment by lierdakil** [comment]
Apparently, the lua filter in question completely ignores anything on the code block except `caption` and `name`. If it used code block's identifier for the image it generates, it would work with pandoc-crossref out of the box. It's a simple change, too, something along the lines of
```lua
if block.identifier then
    imgObj.identifier = block.identifier
end
```
somewhere around [this line](https://github.com/pandoc/lua-filters/blob/b35124a6fd8ef7485e65795e894ccbe6187e657b/diagram-generator/diagram-generator.lua#L320) should work I think (bear in mind it's from the top of my head, so may need some tweaks to actually work)

As it is though, there's no way as far as I can tell, since diagram-generator basically strips any information that pandoc-crossref would use.

**Comment by ctsa** [comment]
Thanks for the suggestion. I will try this and submit a PR to diagram generator if I can get something working.

**Comment by ctsa** [comment]
Confirmed your suggestion worked. PR merged already (https://github.com/pandoc/lua-filters/pull/131) Thanks for your help!
