### ISSUE TITLE
secLabels do not work

### ISSUE THREAD

**Issue by alpianon** [lierdakil/pandoc-crossref#283]
According to the [documentation](https://github.com/lierdakil/pandoc-crossref/blob/1b08cb9b9db04f1997dbfb912d0327bd8f46eff1/docs/index.md#custom-numbering) one may choose a [custom numbering scheme](https://github.com/lierdakil/pandoc-crossref/blob/1b08cb9b9db04f1997dbfb912d0327bd8f46eff1/docs/index.md#custom-numbering-schemes) (arabic, roman, alpha x, list of strings) for figures, tables, sections, etc.

However, this actually works for figures, tables, etc. but not for sections.

Given the following `input.md`:

```md
---
numberSections: true
sectionsDepth: -1
secLabels: alpha a
figLabels: alpha a
tblLabels: roman
---

# First Level Section

## Second Level Section

![my figure](myfig.png){#fig:myfig}

## Other Second Level Section

a   b   c
--- --- ---
1   2   3
4   5   6

: My table {#tbl:mytable}

```

if I convert it with 

```bash
pandoc -t markdown --filter=pandoc-crossref --atx-headers -o output.md input.md
```

I get the following `output.md`:

```md
# 1 First Level Section

## 1.1 Second Level Section

![Figure a: my figure](myfig.png){#fig:myfig}

## 1.2 Other Second Level Section

::: {#tbl:mytable}
  a   b   c
  --- --- ---
  1   2   3
  4   5   6

  : Table I: My table
:::

```

Tables get roman numbers, figures get alpha numbering, but **sections always get standard numbering** (the same happens if I set `secLabels: roman` or `secLabels: [0, 1, 2, 3]`). 

I do not know the internals of pandoc and pandoc-crossref, so I cannot figure out where the bug could be...

**Comment by alpianon** [comment]
Oh, I forgot... I'm using pandoc 2.11.0.2 and pandoc-crossref v0.3.8.3

**Comment by alpianon** [comment]
Last thing: the same happens when I convert to html, docx, etc

**Comment by kappapiana** [comment]
I have noted it too. I thought I was just me being clueless (which i still think, but a little bit less).

**Comment by lierdakil** [comment]
Apparently I just forgot to add a custom numbering handler to sections since those are handled somewhat differently from all the rest (those are also used for tracking chapters, see, so the code path is separate)

I've attempted a fix, but since I'm a bit preoccupied at the moment, I didn't spend much time verifying it -- I only checked that it seems to work on the example in the OP.

Hopefully, the automatic build will be finished in an hour or so (provided it doesn't fail randomly -- which I've seen it do occasionally), and you'll be able to grab the binaries from https://github.com/lierdakil/pandoc-crossref/actions/runs/361656228.

If you could check if those behave more or less as you would expect and tell me if you think it's good to release, that would be great. Thanks in advance.

**Comment by alpianon** [comment]
Simply great! I will test it immediately as binaries are available
Thanks!

**Comment by alpianon** [comment]
I finally managed to make some more in-depth tests, it seems that everything works as expected, thanks!

**Comment by lierdakil** [comment]
Thanks for testing! Publishing as v0.3.8.4.
