### ISSUE TITLE
Latest Windows installer does not seem to work

### ISSUE THREAD

**Issue by parmeshgajjar** [lierdakil/pandoc-crossref#290]
Is there a way of checking that pandoc-crossref installed correctly?

I tried running the installer but a terminal screen flashed and disappeared. When I try running  "--filter pandoc-crossref" I get 

Error running filter pandoc-crossref:
Could not find executable pandoc-crossref

**Comment by lierdakil** [comment]
It's not an installer. It's just an executable. A console executable at that -- that's why the terminal flashed. To run with `--filter pandoc-crossref` you need to either have `pandoc-crossref.exe` in the current directory, have it somewhere on PATH, or have it in pandoc's user filters directory. See [Pandoc manual](https://pandoc.org/MANUAL.html#option--filter) for details.
