### ISSUE TITLE
Request: option to change IDs to final numbering

### ISSUE THREAD

**Issue by cysouw** [lierdakil/pandoc-crossref#291]
Would it be possible to change the IDs of the anchors (i.e the actual sec, fig, tbl) to the number as produced in the actual output? Currently the IDs use the internal name that is used for the cross-referencing. I would very much like to have an option to change these IDs to the actual numbers of the output.

The reason behind this is that I am currently trying to set up an approach that uses hash-fragment-IDs to link to parts inside of webpages. So, if I have a webpage with a table number 4.4 then I would like to refer to this table by using `#tbl:4.4` at the end of the webpage-url.

See the following pandoc filters in which I have already implemented this system for paragraphs and linguistic examples:

https://github.com/cysouw/pandoc-ling
https://github.com/cysouw/count-para

**Comment by lierdakil** [comment]
At the moment, I don't see the way to make it work consistently save for doing an additional pass over all elements and rewriting all links, and frankly that's a bit much work for a very niche application. Besides, are you sure this is a good idea? Because something as simple as inserting another figure will inevitably lead to broken links in this approach. Semantically meaningful identifiers seem much more robust in this regard (e.g. `#fig:floating-point-numbers-density` or something), and that is also preferable in terms of SEO and in terms of knowing what you're clicking on before doing so.

If you're dead-set on this approach, I can suggest post-processing pandoc-crossref's output. At present, it is perhaps harder than it should be, but as a slight simplification I can add an option to add `label` property to objects which would contain the numeric label pandoc-crossref outputs (e.g. `label="1.2.3"` for "Figure 1.2.3"). That said, I can't give a definite timeline of when I will be able to implement this behaviour. Still, I want to check first if it's something that you suppose would be actually useful in your use case.

**Comment by cysouw** [comment]
As for the broken links: this is only supposed to work on final output. The idea is to use it for "published" final versions, so there should be no changes anymore. In that use-case, any revision of the original document will get new URLs anyway, so the links would always go to the right document (namely the old one).

That said: your proposal for an addition `label` attribute would be completely sufficient for me! I can easily change them with a simple lua filter.

If I see it correctly in your output: Headers and Images simply have their own ID. However, tables are put in a div that has the ID (will you be changing that to the new format?).

and: I am not in a hurry :-)

**Comment by lierdakil** [comment]
> If I see it correctly in your output: Headers and Images simply have their own ID. However, tables are put in a div that has the ID (will you be changing that to the new format?).

Tables didn't support attributes/identifiers for a long time, and I'm not convinced all writers caught up with the new format (pretty sure docx didn't), so I won't be moving to that yet.

**Comment by lierdakil** [comment]
I've managed to slap something together in 8cd953b5ef538733ef6a92fdbff738c4c377da66. You can grab binaries from github actions once that finishes. Test it out and let me know if it works for you.

**Comment by lierdakil** [comment]
Released in v0.3.10.0. Feel free to open a new issue if I missed something.

**Comment by cysouw** [comment]
Works perfectly! I have written a quick-and-dirty Lua Filter to change the IDs in the HTML output:

https://github.com/cysouw/crossref-adapt

To see why I am interested in this, check out this short write-up about scientific publishing in the Open Web:

https://github.com/cysouw/openwebpublishing
