### ISSUE TITLE
Combination of cross-reference and implicit heading reference

### ISSUE THREAD

**Issue by skystar0227** [lierdakil/pandoc-crossref#315]
I would like to combine cross-reference and implicit heading reference such as the following example:

```markdown
---
autoSectionLabels: True
linkReferences: True
---

# Section One

This section's heading has an identifier `#sec:section-one` thanks to Pandoc extension auto_identifiers and an option `autoSectionLabels: True` for pandoc-crossref.

Reference styles:

1. See sec. [1](#sec:section-one). : Markdown style
2. See sec. [1][Section One]. : Pandoc style
3. See [@sec:section-one]. : pandoc-crossref style
4. See [@sec][Section One]. : **My proposal style**
```

Note that style 2 won't work properly due to a problem reported in #314.

For style 1 and 3, users have to write identifier, so users should know how heading text is converted to identifier.

For style 2 and 4, users can write heading text instead of identifier, so users have not to know how heading text is converted to identifier.

Style 4 might break well-discussed and unified notation for cross-references, so better syntax might be found.

Please let me know if there are existing ways like style 4.

Thank you in advance.

**Comment by lierdakil** [comment]
(4) clashes with citations, so not great. (1) and (2) aren't strictly speaking references. Those are just hyperlinks. If you don't need pandoc-crossref's counters and are happy with plain hyperlinks, you don't really need to use pandoc-crossref.

Anyway, the preferred way of using pandoc-crossref is to use section identifiers. There are a couple good reasons for that: 

- Section titles can be rather long in some writing styles. Identifier can be almost arbitrarily short.
- If you use identifiers, if at some point you decide to rename a section, you won't need to crawl all over the document and fix references.

The argument about zero knowledge of identifier conversion rules is... well, call it questoinable. The algorithm is plainly expalined in [Pandoc User's Guide](https://pandoc.org/MANUAL.html#extension-auto_identifiers) -- it is a silent assumption that you've read the user's guide, at the very least parts related to features you want to use.

I honestly can't remember why `autoSectionLabels` were introduced, but 6 years later it looks to me like a flawed idea with a flawed execution. Now that I think about it, I'm tempted to remove it altogether rahter than fix its issues (that said, I won't remove it in the 0.3.x version range because backwards compatibility is a thing).

That is not to say I don't understand the reasoning -- pandoc allows referencing sections by title text, so why doesn't pandoc-crossref? Well, let's see.

The reference syntax is `@pfx:some-identifier-without-spaces`, which works this way precisely because it's hacked on top of pandoc's citation syntax. Most section titles will contain spaces. Which means we can't piggyback on pandoc's citation syntax any longer.

Are there alternatives? Well, not really, no.

For one, we don't want to steal too too much syntax for the purpose of references.

For two, citation groups (i.e. `[@ref1; @ref2; @ref3]`) work well enough for reference groups as well; AFAIK there is no other syntax in Pandoc Markdown that has a similar grouping feature.

Inventing completely new syntax is a giant pain, because we'd need to reparse the AST, i.e. convert the AST back to plaintext and parse it again. Suffice to say that AST->plaintext conversions are, generally speaking, lossy in pandoc.

Perhaps there's a way to make it work using some obscure combination of syntactic elements, but after a point I think it's prudent to stop and rethink if we really need this. So, do we?

I have a hard time coming up with reasons for this to be implemented, besides `autoSectionLabels` being not very useful and/or consistent. Considering I believe it's the first time in 6 years this came up, it seems `autoSectionLabels` doesn't see much use anyway. Whether because its implementation is flawed or because it's not that useful to begin with I can not say.

So... as it is, I'm really not sure the effort of improving on `autoSectionLabels` is really worth it. Feel free to try to convince me otherwise.

Maybe I'm just inventing reasons for being lazy. But feature creep is a real issue for this project. At this point, the code base is a bit too large to fit into my head entirely, so adding new features without breaking everything else becomes exponentially hard.

**Comment by skystar0227** [comment]
Your polite description has made me understand how not easy my proposal is. I was too optimistic to request a big feature without any realistic proposals.

FYI, I mention my thought why I prefer to title text instead of identifiers against tool policy.

1. identifier conversion rules make me confused when title text includes Unicode characters.
    - It took so long time from me to find that title text "日本語・英語" is converted to "日本語英語" as identifier.
    - I off course read the Pandoc User's Guide carefully but it does not describe Pandoc perfect specifications.
2. I use Pandoc and other markdown systems with different identifier conversion rules for one document.
    - It is difficult to apply unified rule so I would like to let my markdown documents independent from conversion rules.

It is a little pity for me that `autoSectionLabels` would be not recommended because I feel bored to define identifiers to all headings each time.
However, this is not a longer support request of `autoSectionLabels`.

Anyway, your work is great and I have been satisfied with this discussion.
Thank you for consideration.
