### ISSUE TITLE
Issue with references from TEX - DOCX, figure #'s and references not showing. Other resolved issues did not work for me.

### ISSUE THREAD

**Issue by Aaron-Purchase** [lierdakil/pandoc-crossref#338]
pandoc document.tex --filter pandoc-crossref --bibliography=References/References.bib --csl=ieee.csl -o document.docx

WARNING: pandoc-crossref was compiled with pandoc 2.16.1 but is being run through 2.16.2. This is not supported. Strange things may (and likely will) happen silently.

**Comment by lierdakil** [comment]
TL;DR tex input is not supported, but in practical cases you could convert to Markdown with a little effort. You need to employ an additional filter to convert TeX references to Markdown references, though. See https://github.com/lierdakil/pandoc-crossref/issues/250#issuecomment-596109229 for more information.

Converting from TeX in general isn't ever going to be supported because Pandoc's document model can't handle TeX in general (which is not a surprise, TeX is Turing-complete).
