### ISSUE TITLE
Pandoc 2.17 is out, off by one error with mismatched version

### ISSUE THREAD

**Issue by piccolbo** [lierdakil/pandoc-crossref#339]
Not only that, but it comes with brew. This generates this warning

WARNING: pandoc-crossref was compiled with pandoc 2.16.1 but is being run through 2.17.0.1. This is not supported. Strange things may (and likely will) happen silently.

For full disclosure, this warning happened even with 2.16 because there was a mismatch in the patch number. I observed one problem using the mismatched versions together. For some reason I started my document with a level 2 header (or ## in markdown). This caused a certain section to be numbered 1.6, but references to it were numbered 2.6. When I promoted the first header to level 1 or # the two numbers converged to 2.6. I don't know if the problem would go away with matching versions because brew is unable to backtrack to 2.16.1 or I didn't use the correct incantation. I know from the intro that you are aiming to build against the latest pandoc, but I don't know where the responsibility for what is available with brew resides.

**Comment by piccolbo** [comment]
I cloned the repo and built crossref with stack install. It keeps saying it's built on pandoc 2.16. AFAIK, I have 2.2 and 2.17 in my system, but I don't know where 2.16 could come from.

**Comment by lierdakil** [comment]
Could you provide a minimal example reproducing the bug?

Stack pins dependencies, so pandoc 2.16 comes from stack. That's actually a good thing, because there's no guarantee pandoc-crossref would even build with pandoc 2.17, or if it would, that tests would pass.

I'll try to make a new build available soon-ish.

**Comment by piccolbo** [comment]
Couldn't attach the epub for unknown reason so I took a screenshot. The reference as in epub reads section 2.1 but the book stops at 1.1


[test.md](https://github.com/lierdakil/pandoc-crossref/files/7922561/test.md)
<img width="1070" alt="test" src="https://user-images.githubusercontent.com/905563/150720984-9afd216f-c8a2-46cd-8935-e9522a44337c.png">

**Comment by lierdakil** [comment]
Ah, I see. That's a bit of a quirk with section numbering, yes. Technically a bug, but it kind of makes sense (if you're familiar with idiosyncrasies of pandoc and pandoc-crossref). I'll see if I can tweak the behaviour in the next release, it's not like I don't see the issue here. That said, let me explain what's going on.

If you let pandoc-crossref handle section numbering, e.g.

```bash
pandoc -F pandoc-crossref -Mchapters --top-level-division=chapter -MnumberSections -MsectionsDepth=2 -MchaptersDepth=1 -t markdown test.md 
```

then it all makes a little more sense:

```markdown
## 1.1 Intro

See sec. 2.1

# 2 Chapter Uno

## 2.1 Chapter Uno-Uno {#sec:Uno-Uno}
```

the gist of it is, pandoc-crossref assumes there's an implicit first chapter if your document starts with a sencond-level header. Pandoc itself however starts from 0.

There is a workaround, you can explicitly mark the "Intro" here as unnumbered:

```markdown
## Intro {.unnumbered}

See @sec:Uno-Uno

# Chapter Uno

## Chapter Uno-Uno {#sec:Uno-Uno} 
```

This also avoids the ugly `0.1` with pandoc's section numbers.

**Comment by lierdakil** [comment]
https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.12.2 built with pandoc v2.17.0.1 is released. It also tweaks the numbering behaviour to match pandoc's, see the changelog for details.
