### ISSUE TITLE
Pandoc Types dependency blocks update on Conda-Forge

### ISSUE THREAD

**Issue by mfhepp** [lierdakil/pandoc-crossref#351]
@mfansler was kind enough to update the recipe ("feedstock") that makes pandoc-crossref available for the `conda` package manager at 

https://github.com/conda-forge/pandoc-crossref-feedstock/pull/56

> All is passing, but please comment on pandoc-types before merging (not my expertise):
> 
> Upstream has a dependency on pandoc-types, but I don't find this on Conda Forge - do we need a new feedstock for this?
> 
> Even if we don't need it for build or run, perhaps we should be adding bounds under run_constrained.
> 

Unfortunately, his readily deployable pull-request is pending review because of an intransparent dependency on `pandoc-types`.

It would be great if you @lierdakil  could clarify if this dependency is really needed.

Thanks!

**Comment by mfansler** [comment]
This was the clarification I was looking for: https://github.com/conda-forge/pandoc-crossref-feedstock/pull/56#issuecomment-1168257956

In summary, while Conda Forge packaging continues to be a redistribution of executables from this repository, it remains unnecessary for us to include any `pandoc-types` constraints since it is a build-time-only requirement. However, were we to switch to direct compilation (e.g., https://github.com/conda-forge/pandoc-feedstock/issues/54), then we will need to incorporate it.

My concern has been resolved (feel free to close), and thanks again @mfhepp for pushing the discussion forward.

**Comment by lierdakil** [comment]
I was out of town, didn't see this notification until now. AFAIU this is resolved?
