### ISSUE TITLE
section reference in appendix

### ISSUE THREAD

**Issue by hadim** [lierdakil/pandoc-crossref#37]
Does `{#sec:label}` works when specified after `\appendix` and called in the main text before `\appendix` with something like that `@sec:label`.

In my case it generates the following : `Section ??`

Any idea ?

**Comment by lierdakil** [comment]
Okay, so `{#sec:label}` will only work with section headings, i.e. `# Heading {#sec:label}` or 

```markdown
Heading {#sec:label}
===============
```

Raw LaTeX commands are just that -- raw LaTeX commands, those 
a) don't work with other output formats
b) are not parsed as semantic document elements

If you only need LaTeX output, you might have better luck with raw latex, without pandoc and whatnot.

**Comment by hadim** [comment]
Sorry I didn't specified that `{#sec:label}` was used with section heading after `\appendix`. The following : 

```latex
\appendix
# Appendix
## My appendix One {#sec:appendix_one}
```

does not work.

As a workaround I currently use raw LaTex but it's obiouvsly not the right thing to do since I installed `pandoc-crossref`, the purpose was toi avoid LaTex command and be format independant...

**Comment by lierdakil** [comment]
This should work. I will test and try to figure out what goes wrong for
you. Probably sometime this weekend.
8 окт. 2015 г. 11:21 пользователь "Hadrien Mary" <notifications@github.com>
написал:

**Comment by hadim** [comment]
Thanks @lierdakil !

**Comment by lierdakil** [comment]
Okay, I've banged my head for a bit, since I rarely work with LaTeX these days, but here's your answer: you need to run pandoc with `--number-sections` to assign numbers to sections. If you don't, neither `\ref` nor `\cref` will know how to reference it... That goes for more than just appendix, btw.

Output formats other than LaTeX will work fine regardless, but `--number-sections` is advised anyway, since otherwise, navigating section references becomes unnecessarily hard.

**Comment by hadim** [comment]
Thanks @lierdakil
