### ISSUE TITLE
custom numbering scheme

### ISSUE THREAD

**Issue by danil-tolkachev** [lierdakil/pandoc-crossref#64]
What is the syntax for numbering scheme of labels (`figLabels`, `subfigLabels` etc.)? From `readme.md` I know only about `default` (arabic numbers) and `alpha a` (small latin letters). Is it possible to use other  alphabets? I'm interested in russian alphabet support.

**Comment by lierdakil** [comment]
Oh dear. I think I actually forgot to write a section on custom numbering.

You have choice between:
- `arabic` -- arabic numbers (1, 2, 3 ...)
- `roman` -- roman numbers (I, II, III, IV, ...)
- `alpha x`, where `x` is first letter to start of. This will work for any letter, but will use UTF-8 codepage to determine what's next, so using something strange is not advised. You can safely use `alpha <russian a>` to get lowercase russian letters for 32 figures. After that, it will get weird (since russian alphabet has 32 letters -- not counting `ё`). Specifically, it will go into sub-national cyrillic space (`ѐ`, `ё`, `ђ`, etc). You can consult http://www.fileformat.info/info/unicode/block/cyrillic/utf8test.htm for general idea on letter progression.
- list of strings. You can define a YAML array for numbers. Mapping is 1:1. For example, 
```yaml
figLabels: [α, β, γ, 1, 2, 3, I, II, III]
```
will give first figure label 'α', second -- 'β', etc.

Note that it will repeat last item in list indefinitely if there are more images than items in list (I probably should throw an error, but that's not there at the moment)

**Comment by danil-tolkachev** [comment]
That's cool features. Thanks.

**Comment by lierdakil** [comment]
Finally got around to adding this to docs.
