### ISSUE TITLE
Issue with underscore in section labels

### ISSUE THREAD

**Issue by Phyks** [lierdakil/pandoc-crossref#66]
Hi,

When defining a `#Section {#sec:convergence_speed}`, the produced LaTeX for the label is `\label{sec:convergenceux5fspeed}`.

However, when using a `[@sec:convergence_speed]`, the produced citation LaTeX is `\cref{sec:convergence_speed}`.

Then, the reference fails, as the label is not defined in the same way as the citation.

As
```
>>> b"\x5f".decode("utf-8")
'_'
```

it seems to be due to a charset decoding / escaping error.

**Comment by lierdakil** [comment]
Technically, this is an issue with Pandoc, since minimal example produces invalid output:

```
$ pandoc -t latex <<< "#Section {#section_label}"
\section{Section}\label{sectionux5flabel}
```

That said, I think using `_` in LaTeX identifiers is discouraged. Solution? Use hyphens.

Nonetheless, I will push a 'fixed' version shortly, which uses the same `ux5f` replacement for underscores as Pandoc.

**Comment by Phyks** [comment]
Thanks!

Is it worth posting an issue upstream?

**Comment by lierdakil** [comment]
I'm not entirely sure if it's a bug or a feature, to tell the truth. I guess it's worth a shot, since a quick search doesn't turn up any relevant discussions. If you do, mention me in the issue text (e.g. `/cc @lierdakil`), so that I get notified of discussion.
