### ISSUE TITLE
support for formatting of labels

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#8]
Often, labels are printed in bold or italics, i. e. 

**Figure 1**: The solar system.

It would be great to use markdown syntax in the YAML parameters to format the table and figure labels. I. e. `-M "figureTitle:**Figure #**"`

BTW: In Latex it works out of the box because it can be configured with the package ccaption, for instance.

**Comment by lierdakil** [comment]
You actually can format "Figure" word itself, if needed -- you only have to specify `figureTitle` inside YAML metadata, since it's not parsed as Markdown otherwise (it's pandoc limitation, mostly, and it's a huge pain to circumvent, to tell the truth). Number is not formatted this way though.

I could probably implement something like `figureTemplate` etc metadata options, but I need some time to consider possible formats for it.

**Comment by lierdakil** [comment]
I think I could leverage display math syntax for template variables, since display math doesn't make much sense in captions anyway.

E.g.
```yaml
figureTitle: Figure
figureTemplate: **$$figureTitle$$ №$$i$$**
```

It is a hacky solution, but all other options require either relatively complex parsing, or offer much less in way of customisation.

**Comment by tolot27** [comment]
Great idea! :+1: 

Math anywhere in captions is not so unusual, but I've never seen math in caption labels.

**Comment by lierdakil** [comment]
Well, with this one can still use inline math even in caption labels. Display math breaks paragraph flow though, so it would be a *very* peculiar use-case.

**Comment by lierdakil** [comment]
Okay, implemented in `master`. Should work. As an added bonus, variables specified on command line are parsed as default Pandoc Markdown.
Note that display math not recognized as a variable will be left as-is. This might change in the future though.

**Comment by tolot27** [comment]
Works like a charme, even with command line parameters.
