### ISSUE TITLE
ability to configure prefix rendering

### ISSUE THREAD

**Issue by olaurino** [lierdakil/pandoc-crossref#83]
Would it be possible to configure how a certain prefix is rendered by the filter? For instance, I would like to be able to suppress the rendering in the first place, so that for example I can write `see Appendix [@sec:ThisIsAnAppendix]` and not visualize the default `sec.` text.

Additionaly, it could be useful to define additional prefixes and their renderings, so I could define `app -> app.` as a mapping from the `app` prefix to the `Appendix` rendering.

I have no experience whatsoever with Haskell, so I would not even know where to start to issue a PR, sorry :)

**Comment by lierdakil** [comment]
I guess I could use citation prefix for the first one., e.g. `see [Appendix @sec:Appendix]`.

Might also be useful to differentiate between `[@reference]` and `@reference` -- second version could only output numbers. That would have to be hidden behind an option though, to keep backward compatibility.

Custom prefixes sound reasonable, but implementation might prove convoluted. So I'll see what I can do there, but that might take a while.

**Comment by olaurino** [comment]
Well, thank you for looking into it! I wish I could help, but this is not the right time for me to learn Haskell :)

**Comment by lierdakil** [comment]
Citation prefix substitution/suppression implemented in `master`. You can clone and build it (I highly recommend using [stack](http://haskellstack.org)):

```
git clone https://github.com/lierdakil/pandoc-crossref
cd pandoc-crossref
stack install pandoc pandoc-citeproc pandoc-crossref
```

(you can run `stack path --local-bin` to see where binaries will actually be installed -- usually `$HOME/.local/bin` on *nix, and I have no idea where on Windows, probably somewhere in `C:\Users\`)

Build might take a while though

Note that for the sake of consistency, you should use built versions of pandoc and pandoc-citeproc as well, if you choose to do this.

#### Usage

Prefix substitution: `[Prefix @citation]` will replace default prefix (`fig.`/`sec.`/etc) with prefix verbatim, e.g. `[Prefix @fig:1]` will be rendered as `Prefix 1` instead of `fig. 1`.

In citation group, citations with the same prefix will be grouped. So, for example `[A @fig:1; A @fig:2; B @fig:3]` will turn into `A 1, 2, B 3`. It can be used to an advantage, although it's a bit more cumbersome than it should be, e.g. `[Appendices @sec:A1; Appendices @sec:A2; Appendices @sec:A3]` will turn into `Appendices @A1-@A3` (with `@A1` and `@A3` being relevant section numbers). Note that non-contiguous sequences of identical prefixes *will not* be grouped.

Prefix suppression: `[-@citation]` will suppress default prefix, e.g. `[-@fig:1]` will produce just `1` without `fig.` prefix.

In citation group, citations with and without prefixes will be in different groups. So `[-@fig:1; @fig:2; -@fig:3]` will be rendered as `1, fig. 2, 3`, so be careful with this feature. Again, non-contiguous sequences are not grouped together.

**Comment by olaurino** [comment]
Wonderful! Thanks a lot!
