### ISSUE TITLE
Docx rendering doesn't use Image Caption style

### ISSUE THREAD

**Issue by mangecoeur** [lierdakil/pandoc-crossref#87]
By default in pandoc, when rendering to word docx all image captions pick up the 'caption' style - so if you use a word document as a template for example the caption styles will be correctly applied.

For some reason when using pandoc crossref the captions no longer have the caption style applied.

**Comment by lierdakil** [comment]
For individual images and tables this should work. Please check your setup.

As for subfigure block captions, code block captions, etc, pandoc-crossref may have to use plain paragraphs for captions, in which case Pandoc won't apply any styles to those. I have no solution in this case. At least I can say I won't support docx directly, like LaTeX, due to it being a nightmare to work with.

**Comment by lierdakil** [comment]
Well, with pandoc-1.18, we have a solution, apparently: http://pandoc.org/MANUAL.html#custom-styles-in-docx-output
Pandoc-crossref needs to be modified to make use of this feature still, but it's a plan at least.

**Comment by mangecoeur** [comment]
Great, at least there is an easier path to a solution now

**Comment by lierdakil** [comment]
Okay, I've made the changes necessary, so it should work reasonably well with pandoc-1.18 (although listings don't have a dedicated style, so those will end up as just 'Caption')
If you could verify that it works for you (by building from `master` -- use `stack-pandoc118.yaml` if building with stack) -- that'd be nice.

**Comment by mangecoeur** [comment]
Sure will do as soon as I can

**Comment by lierdakil** [comment]
I've pushed 0.2.4.1 on hackage, which should include the fix. Feel free to open new issues if something doesn't work as expected.
