### ISSUE TITLE
Pandoc 1.18 breaks compatibility

### ISSUE THREAD

**Issue by mickley** [lierdakil/pandoc-crossref#92]
Pandoc 1.18 apparently made a small change to the JSON format that requires all filters to be updated: http://pandoc.org/releases.html

Currently it gives the following error:

```
ERROR:     !pandoc-crossref: when expecting a product (:*:), encountered Object instead
ERROR:   failed to receive json object from filter---skipping filter
```

**Comment by lierdakil** [comment]
You can try building `master` against pandoc-1.18. I'll try to do a release sometime in November.

**Comment by acidghost** [comment]
Is there a quick fix for this?

**Comment by lierdakil** [comment]
@acidghost, depends on what exactly you call 'quick'.

Get a Haskell Platform or similar (ghc and cabal at minimum), get git, clone this repo, in the root of the work tree run

```
cabal sandbox init
cabal install pandoc-citeproc
cabal install
```

You should then get all binaries in `.cabal-sandbox/bin`. This will take a while though.

If you're on windows, I believe I can provide a prebuilt executable. Can't do that on mac due to lack of a working OSX installation, and on linux it's a bit of a headache due to a wide array of libc and kernel versions, so not much luck there as well (but I can try)

**Comment by acidghost** [comment]
I'm trying your suggestion on Ubuntu right now. Will update here.

**Comment by mickley** [comment]
Yes, sorry it worked for me as well

**Comment by BafS** [comment]
Is their a fix available without cabal ?

I have this error

```
pandoc-citeproc: when expecting a product (:*:), encountered Object instead
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

Thanks !

**Comment by lierdakil** [comment]
> it does work !

Glad to hear that.
